//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WizardWrx.ConsoleStreams.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WizardWrx.ConsoleStreams.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{{0} (Text (Foreground) = {1}, Background = {2})}}.
        /// </summary>
        internal static string CONSOLE_COLORS_TOSTRING_TEMPLATE {
            get {
                return ResourceManager.GetString("CONSOLE_COLORS_TOSTRING_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{{0} (Fatal: Text (Foreground) = {1}, Background = {2}; Recoverable: Text (Foreground) = {3}, Background = {4})}}.
        /// </summary>
        internal static string DEFAULTERRORMESSAGECOLORS_TOSTRING_TEMPLATE {
            get {
                return ResourceManager.GetString("DEFAULTERRORMESSAGECOLORS_TOSTRING_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected exception arose in method {0}.{3}    Exception HResult = {1}{3}    Exception Message = {2}{3}    Additional details are in the inner exception..
        /// </summary>
        internal static string ERRMSG_UNEXPECTED_SAFE_CLEAR_SCREEN_EXCEPTION {
            get {
                return ResourceManager.GetString("ERRMSG_UNEXPECTED_SAFE_CLEAR_SCREEN_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM ERROR: The required Windows system routines are unavailable on the installed version of Microsoft Windows, version {0}{1}.{4}The minimum supported version is {2}.{3}..
        /// </summary>
        internal static string ERRMSG_UNSUPPORTED_WINDOWS_VERSION {
            get {
                return ResourceManager.GetString("ERRMSG_UNSUPPORTED_WINDOWS_VERSION", resourceCulture);
            }
        }
    }
}
