using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.

// This file is a partial AssemblyInfo.cs for the class libraries that comprise
// the WizardrWrx.DLLServices2 constellation of class librarys that target the
// Microsoft .NET Framework, version 3.5 and above.

[assembly: AssemblyConfiguration ( "" )]
[assembly: AssemblyCompany ( "David A. Gray" )]
[assembly: AssemblyProduct ( "DLLServices" )]
[assembly: AssemblyCopyright ( "Copyright © 2017, David A. Gray" )]
[assembly: AssemblyTrademark ( "This library is distributed under a three-clause BSD license." )]
[assembly: AssemblyCulture ( "" )]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers
// by using the '*' as shown below:
// [assembly: AssemblyVersion ( "1.0.*" )]
[assembly: AssemblyFileVersion ( "7.12.209.*" )]
[assembly: AssemblyInformationalVersion ( "7.12.209.*" )]