//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WizardWrx.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WizardWrx.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{{0} (Per AgedFileInfo Instance: Base Name        = {1},LastWriteTimeUTC = {2} ({3 Ticks}),LastWriteTime    = {4} ({5 Ticks}))}}.
        /// </summary>
        internal static string AGED_FILES_INFO_TOSTRING_TEMPLATE {
            get {
                return ResourceManager.GetString("AGED_FILES_INFO_TOSTRING_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of aliases is empty..
        /// </summary>
        internal static string EMPTY_ALIAS_LIST {
            get {
                return ResourceManager.GetString("EMPTY_ALIAS_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array cannot be empty..
        /// </summary>
        internal static string ERRMSG_ARRAY_IS_EMPTY {
            get {
                return ResourceManager.GetString("ERRMSG_ARRAY_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: The CreateFormatString method cannot process the specified format string.{1}    Specified format string = {0.
        /// </summary>
        internal static string ERRMSG_CANNOT_PARSE {
            get {
                return ResourceManager.GetString("ERRMSG_CANNOT_PARSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , and.
        /// </summary>
        internal static string ERRMSG_COMMA_AND_LITERAL {
            get {
                return ResourceManager.GetString("ERRMSG_COMMA_AND_LITERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: The specified object is a {0}.{2}Type must be {1}..
        /// </summary>
        internal static string ERRMSG_COMPARAND_IS_WRONG_TYPE {
            get {
                return ResourceManager.GetString("ERRMSG_COMPARAND_IS_WRONG_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified DLL configuration file, {0}, exists, but is empty..
        /// </summary>
        internal static string ERRMSG_CONFIG_FILE_IS_EMPTY {
            get {
                return ResourceManager.GetString("ERRMSG_CONFIG_FILE_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while processing the {0} property on a {1} object. Details are as follows: {2}.
        /// </summary>
        internal static string ERRMSG_CONFIG_PROP_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERRMSG_CONFIG_PROP_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: The DetailFormat property cannot be a null reference or empty string..
        /// </summary>
        internal static string ERRMSG_DETAIL_FORMAT_CANNOT_BE_NULL_OR_BLANK {
            get {
                return ResourceManager.GetString("ERRMSG_DETAIL_FORMAT_CANNOT_BE_NULL_OR_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: The DisplayOrder property cannot be set to zero..
        /// </summary>
        internal static string ERRMSG_DISPLAY_ORDER_CANNOT_BE_ZERO {
            get {
                return ResourceManager.GetString("ERRMSG_DISPLAY_ORDER_CANNOT_BE_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property name {0} in configuration file {1} is a duplicate name..
        /// </summary>
        internal static string ERRMSG_DUPLICATE_CONFIG_PROP_NAME {
            get {
                return ResourceManager.GetString("ERRMSG_DUPLICATE_CONFIG_PROP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch {0} with a default value of {1} is a duplicate..
        /// </summary>
        internal static string ERRMSG_DUPLICATE_SWITCH {
            get {
                return ResourceManager.GetString("ERRMSG_DUPLICATE_SWITCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{3}    Input Value   = {1}{3}    Expected Type = {2}{3}.
        /// </summary>
        internal static string ERRMSG_ENUMERATION_CONVERSION {
            get {
                return ResourceManager.GetString("ERRMSG_ENUMERATION_CONVERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An {0} Exception was caught while attempting to define a switch named {1} with a default value of {2}..
        /// </summary>
        internal static string ERRMSG_EXCEPTION_IN_DEFINE_NEW_SWITCH {
            get {
                return ResourceManager.GetString("ERRMSG_EXCEPTION_IN_DEFINE_NEW_SWITCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message from Exception Logged without throwing: {0}.
        /// </summary>
        internal static string ERRMSG_EXCEPTION_NOT_THROWN {
            get {
                return ResourceManager.GetString("ERRMSG_EXCEPTION_NOT_THROWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message from Exception Thrown and Logged: {0}.
        /// </summary>
        internal static string ERRMSG_FROM_THROWN_EXCEPTION {
            get {
                return ResourceManager.GetString("ERRMSG_FROM_THROWN_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error has been detected in routine ReformatSysDate.{2}An unexpected FormattingAlgorithm of {0} has been encountered while processing the following input string:{2}{1}.
        /// </summary>
        internal static string ERRMSG_INTERNAL_ERROR_UNSUPP_ALG {
            get {
                return ResourceManager.GetString("ERRMSG_INTERNAL_ERROR_UNSUPP_ALG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORRUPTED SYSTEM REGISTRY: The GetDisplayTimeZone method found the specified key, but the corresponding Registry key is corrupted.{1}                           Specified ID = {0}.
        /// </summary>
        internal static string ERRMSG_INV_TZINFO {
            get {
                return ResourceManager.GetString("ERRMSG_INV_TZINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no valid configuration file for DLL file {0}..
        /// </summary>
        internal static string ERRMSG_MISSING_CONFIG_FILE {
            get {
                return ResourceManager.GetString("ERRMSG_MISSING_CONFIG_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM RESOURCE FAMINE: The GetDisplayTimeZone method ran out of memory..
        /// </summary>
        internal static string ERRMSG_NO_MEMORY {
            get {
                return ResourceManager.GetString("ERRMSG_NO_MEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERNAL ERROR: The GetDisplayTimeZone method let a null pstrTimeZoneID through to TimeZoneInfo.FindSystemTimeZoneById..
        /// </summary>
        internal static string ERRMSG_NULL_TZ_ID {
            get {
                return ResourceManager.GetString("ERRMSG_NULL_TZ_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: No value has been assigned to this object..
        /// </summary>
        internal static string ERRMSG_REPORT_ITEM_IS_NULL {
            get {
                return ResourceManager.GetString("ERRMSG_REPORT_ITEM_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: This detail object is incomplete. It needs a label..
        /// </summary>
        internal static string ERRMSG_REPORT_ITEM_IS_UNLABELED {
            get {
                return ResourceManager.GetString("ERRMSG_REPORT_ITEM_IS_UNLABELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCESS VIOLATION: The GetDisplayTimeZone method cannot read the Registry keys where the time zone information is kept. The process has insufficient access permissions on that key..
        /// </summary>
        internal static string ERRMSG_SECURITY {
            get {
                return ResourceManager.GetString("ERRMSG_SECURITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Label property of a ReportDetail cannot be null or blank..
        /// </summary>
        internal static string ERRMSG_SPECIFIED_LABEL_IS_NULL_OR_BLANK {
            get {
                return ResourceManager.GetString("ERRMSG_SPECIFIED_LABEL_IS_NULL_OR_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starting at character position {0}{1}{2}.
        /// </summary>
        internal static string ERRMSG_START_CHARACTER {
            get {
                return ResourceManager.GetString("ERRMSG_START_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The InputValue of the fixup pair at ordinal position {0} (subscript = {1}) is a null reference or the empty string.{4}    The OutputValue at that position is {2}, which is {3}..
        /// </summary>
        internal static string ERRMSG_STRING_FIXUP_PAIR_IS_INVALID {
            get {
                return ResourceManager.GetString("ERRMSG_STRING_FIXUP_PAIR_IS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: The value of the report item labeled {0} has not been set..
        /// </summary>
        internal static string ERRMSG_THIS_REPORTITEM_IS_NULL {
            get {
                return ResourceManager.GetString("ERRMSG_THIS_REPORTITEM_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERNAL or DATA ERROR: The GetDisplayTimeZone method let a pstrTimeZoneID that isn&apos;t registered on this computer through to TimeZoneInfo.FindSystemTimeZoneById.{1}                        Specified ID = {0}.
        /// </summary>
        internal static string ERRMSG_TZ_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERRMSG_TZ_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * UNLABELED *.
        /// </summary>
        internal static string ERRMSG_UNLABELED {
            get {
                return ResourceManager.GetString("ERRMSG_UNLABELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INPUT ERROR: Specified input string {0}{2}             contains {1} unresolved environment variable.{2}.
        /// </summary>
        internal static string ERRMSG_UNRESLOVED_ENVIRONEMT_STRINGS {
            get {
                return ResourceManager.GetString("ERRMSG_UNRESLOVED_ENVIRONEMT_STRINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variable.
        /// </summary>
        internal static string ERRMSG_VARIABLE_LITERAL {
            get {
                return ResourceManager.GetString("ERRMSG_VARIABLE_LITERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is an EFI Application..
        /// </summary>
        internal static string IMAGE_SUBSYSTEM_EFI_APPLICATION {
            get {
                return ResourceManager.GetString("IMAGE_SUBSYSTEM_EFI_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is a EFI Boot Service Driver..
        /// </summary>
        internal static string IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER {
            get {
                return ResourceManager.GetString("IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image runs from a EFI ROM..
        /// </summary>
        internal static string IMAGE_SUBSYSTEM_EFI_ROM {
            get {
                return ResourceManager.GetString("IMAGE_SUBSYSTEM_EFI_ROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is a EFI Runtime Driver..
        /// </summary>
        internal static string IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER {
            get {
                return ResourceManager.GetString("IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image doesn&apos;t require a subsystem..
        /// </summary>
        internal static string IMAGE_SUBSYSTEM_NATIVE {
            get {
                return ResourceManager.GetString("IMAGE_SUBSYSTEM_NATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is a native Win9x driver..
        /// </summary>
        internal static string IMAGE_SUBSYSTEM_NATIVE_WINDOWS {
            get {
                return ResourceManager.GetString("IMAGE_SUBSYSTEM_NATIVE_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image runs in the OS/2 character subsystem..
        /// </summary>
        internal static string IMAGE_SUBSYSTEM_OS2_CUI {
            get {
                return ResourceManager.GetString("IMAGE_SUBSYSTEM_OS2_CUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image runs in the Posix character subsystem..
        /// </summary>
        internal static string IMAGE_SUBSYSTEM_POSIX_CUI {
            get {
                return ResourceManager.GetString("IMAGE_SUBSYSTEM_POSIX_CUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified image subsystem ID, {0} is undefined..
        /// </summary>
        internal static string IMAGE_SUBSYSTEM_UNDEFINED_VALUE {
            get {
                return ResourceManager.GetString("IMAGE_SUBSYSTEM_UNDEFINED_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown subsystem..
        /// </summary>
        internal static string IMAGE_SUBSYSTEM_UNKNOWN {
            get {
                return ResourceManager.GetString("IMAGE_SUBSYSTEM_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image runs in the Windows CE subsystem..
        /// </summary>
        internal static string IMAGE_SUBSYSTEM_WINDOWS_CE_GUI {
            get {
                return ResourceManager.GetString("IMAGE_SUBSYSTEM_WINDOWS_CE_GUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image runs in the Windows character subsystem..
        /// </summary>
        internal static string IMAGE_SUBSYSTEM_WINDOWS_CUI {
            get {
                return ResourceManager.GetString("IMAGE_SUBSYSTEM_WINDOWS_CUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image runs in the Windows GUI subsystem..
        /// </summary>
        internal static string IMAGE_SUBSYSTEM_WINDOWS_GUI {
            get {
                return ResourceManager.GetString("IMAGE_SUBSYSTEM_WINDOWS_GUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image runs on XBOX..
        /// </summary>
        internal static string IMAGE_SUBSYSTEM_XBOX {
            get {
                return ResourceManager.GetString("IMAGE_SUBSYSTEM_XBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be greater than zero..
        /// </summary>
        internal static string INCREMENT_CANNOT_BE_ZERO {
            get {
                return ResourceManager.GetString("INCREMENT_CANNOT_BE_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment Property Value.
        /// </summary>
        internal static string INCREMENT_PROPERTY_VALUE {
            get {
                return ResourceManager.GetString("INCREMENT_PROPERTY_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1} UTC).
        /// </summary>
        internal static string LOCAL_AND_UTC_TIME_TEMPLATE {
            get {
                return ResourceManager.GetString("LOCAL_AND_UTC_TIME_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     {0} of {1}: {2} = {3}{4}.
        /// </summary>
        internal static string MSG_ACCEPTED_DEFAULT_VALUE {
            get {
                return ResourceManager.GetString("MSG_ACCEPTED_DEFAULT_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}End of list{0}.
        /// </summary>
        internal static string MSG_ACCEPTED_LIST_END {
            get {
                return ResourceManager.GetString("MSG_ACCEPTED_LIST_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All {0} configuration settings defined for {1} are covered by its configuration file..
        /// </summary>
        internal static string MSG_ALL_CONFIG_SETTINGS_COVERED {
            get {
                return ResourceManager.GetString("MSG_ALL_CONFIG_SETTINGS_COVERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} property default value of {1} accepted in lieu of value in configuration file, which is absent..
        /// </summary>
        internal static string MSG_DEFAULT_ACCEPTED {
            get {
                return ResourceManager.GetString("MSG_DEFAULT_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} configuration settings defined for {2} are missing from its configuration file.{3}{3} Details follow.{3}{3}.
        /// </summary>
        internal static string MSG_SOME_CONFIG_SETTINGS_OMITTED {
            get {
                return ResourceManager.GetString("MSG_SOME_CONFIG_SETTINGS_OMITTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at System.Environment.get_StackTrace().
        /// </summary>
        internal static string MSG_STACK_TRACE_IS_FROM_ENVIRONMENT {
            get {
                return ResourceManager.GetString("MSG_STACK_TRACE_IS_FROM_ENVIRONMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2}Processor Architecture = {0}{2}Process Machine Word   = {1} bits{2}.
        /// </summary>
        internal static string PROCESSOR_AND_PROCESS_ARCHITECTURES {
            get {
                return ResourceManager.GetString("PROCESSOR_AND_PROCESS_ARCHITECTURES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string SWITCH_IS_OFF {
            get {
                return ResourceManager.GetString("SWITCH_IS_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string SWITCH_IS_ON {
            get {
                return ResourceManager.GetString("SWITCH_IS_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{{0} ({1})}}.
        /// </summary>
        internal static string SYNCROOT_TOSTRING_TEMPLATE {
            get {
                return ResourceManager.GetString("SYNCROOT_TOSTRING_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of {1} specified for argument {0} is invalid..
        /// </summary>
        internal static string TDF_INVALID_ARG_VALUE {
            get {
                return ResourceManager.GetString("TDF_INVALID_ARG_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new value of {1} specified for the {0} property is invalid.{3}The previous value of {2} is retained..
        /// </summary>
        internal static string TDF_INVALID_ENUM_VALUE {
            get {
                return ResourceManager.GetString("TDF_INVALID_ENUM_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string TIME_LABEL_LOCAL_LONG {
            get {
                return ResourceManager.GetString("TIME_LABEL_LOCAL_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC.
        /// </summary>
        internal static string TIME_LABEL_LOCAL_SHORT {
            get {
                return ResourceManager.GetString("TIME_LABEL_LOCAL_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTC.
        /// </summary>
        internal static string TIME_LABEL_UTC {
            get {
                return ResourceManager.GetString("TIME_LABEL_UTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties of the Exception object returned by TraceLogger.WriteWithBothTimesLabeledLocalFirst: Message                        = {0}.
        /// </summary>
        internal static string TRACEMSG_EXCEPTION_NOT_THROWN_1 {
            get {
                return ResourceManager.GetString("TRACEMSG_EXCEPTION_NOT_THROWN_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source                         = {0}.
        /// </summary>
        internal static string TRACEMSG_EXCEPTION_NOT_THROWN_2 {
            get {
                return ResourceManager.GetString("TRACEMSG_EXCEPTION_NOT_THROWN_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TargetSite.Name                = {0}.
        /// </summary>
        internal static string TRACEMSG_EXCEPTION_NOT_THROWN_3 {
            get {
                return ResourceManager.GetString("TRACEMSG_EXCEPTION_NOT_THROWN_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StackTrace                     = {0}.
        /// </summary>
        internal static string TRACEMSG_EXCEPTION_NOT_THROWN_4 {
            get {
                return ResourceManager.GetString("TRACEMSG_EXCEPTION_NOT_THROWN_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InnerException.Message         = {0}.
        /// </summary>
        internal static string TRACEMSG_EXCEPTION_NOT_THROWN_5 {
            get {
                return ResourceManager.GetString("TRACEMSG_EXCEPTION_NOT_THROWN_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InnerException.Source          = {0}.
        /// </summary>
        internal static string TRACEMSG_EXCEPTION_NOT_THROWN_6 {
            get {
                return ResourceManager.GetString("TRACEMSG_EXCEPTION_NOT_THROWN_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InnerException.TargetSite.Name = {0}.
        /// </summary>
        internal static string TRACEMSG_EXCEPTION_NOT_THROWN_7 {
            get {
                return ResourceManager.GetString("TRACEMSG_EXCEPTION_NOT_THROWN_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InnerException.StackTrace      = {0}.
        /// </summary>
        internal static string TRACEMSG_EXCEPTION_NOT_THROWN_8 {
            get {
                return ResourceManager.GetString("TRACEMSG_EXCEPTION_NOT_THROWN_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;                                                                                                InnerException                 = [null].
        /// </summary>
        internal static string TRACEMSG_EXCEPTION_NOT_THROWN_9 {
            get {
                return ResourceManager.GetString("TRACEMSG_EXCEPTION_NOT_THROWN_9", resourceCulture);
            }
        }
    }
}
