//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WizardWrx.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WizardWrx.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        public static string ANSWER_IS_FALSE {
            get {
                return ResourceManager.GetString("ANSWER_IS_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string ANSWER_IS_NO {
            get {
                return ResourceManager.GetString("ANSWER_IS_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string ANSWER_IS_TRUE {
            get {
                return ResourceManager.GetString("ANSWER_IS_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string ANSWER_IS_YES {
            get {
                return ResourceManager.GetString("ANSWER_IS_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WizardWrx.
        /// </summary>
        public static string DEFAULT_EVENT_SOURCE_ID_STRING {
            get {
                return ResourceManager.GetString("DEFAULT_EVENT_SOURCE_ID_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified argument is a null reference..
        /// </summary>
        public static string ERRMSG_ARG_IS_NULL {
            get {
                return ResourceManager.GetString("ERRMSG_ARG_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument is a null reference or the empty string..
        /// </summary>
        public static string ERRMSG_ARG_IS_NULL_OR_EMPTY {
            get {
                return ResourceManager.GetString("ERRMSG_ARG_IS_NULL_OR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of {0} is out of range; it must be between {1} and {2}..
        /// </summary>
        public static string ERRMSG_ARG_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("ERRMSG_ARG_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array {0} ie empty; it exists, but contains no elements..
        /// </summary>
        public static string ERRMSG_ARRAY_IS_EMPTY {
            get {
                return ResourceManager.GetString("ERRMSG_ARRAY_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process string {0}.
        /// </summary>
        public static string ERRMSG_BADSTRING {
            get {
                return ResourceManager.GetString("ERRMSG_BADSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The empty string is never valid in this context..
        /// </summary>
        public static string ERRMSG_EMPTY_STRING_NEVER_VALID {
            get {
                return ResourceManager.GetString("ERRMSG_EMPTY_STRING_NEVER_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file {0} is empty..
        /// </summary>
        public static string ERRMSG_FILE_IS_EMPTY {
            get {
                return ResourceManager.GetString("ERRMSG_FILE_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file {0} cannot be found..
        /// </summary>
        public static string ERRMSG_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERRMSG_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the first argument, pintegralValue, is invalid.{2}Argument value = {0}{2}Argument type  = {1}{2}{2}Limitations of the underlying formatting engine{2}restrict this method to integral types.{2}.
        /// </summary>
        public static string ERRMSG_INTEGER2HEXSTR_INVALID_INPUT {
            get {
                return ResourceManager.GetString("ERRMSG_INTEGER2HEXSTR_INVALID_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one command line argument is invalid..
        /// </summary>
        public static string ERRMSG_INVALID_COMMAND_LINE {
            get {
                return ResourceManager.GetString("ERRMSG_INVALID_COMMAND_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file {0}, record {1} is invalid..
        /// </summary>
        public static string ERRMSG_INVALID_FIELD_IN_INPUT_RECORD {
            get {
                return ResourceManager.GetString("ERRMSG_INVALID_FIELD_IN_INPUT_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A null reference to a string is never valid in this context..
        /// </summary>
        public static string ERRMSG_NULLREF_NEVER_VALID {
            get {
                return ResourceManager.GetString("ERRMSG_NULLREF_NEVER_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0} is a null reference..
        /// </summary>
        public static string ERRMSG_REFERENCE_IS_NULL {
            get {
                return ResourceManager.GetString("ERRMSG_REFERENCE_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A run-time exception has occurred..
        /// </summary>
        public static string ERRMSG_RUNTIME {
            get {
                return ResourceManager.GetString("ERRMSG_RUNTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task completed successfully..
        /// </summary>
        public static string ERRMSG_SUCCESS {
            get {
                return ResourceManager.GetString("ERRMSG_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLANK.
        /// </summary>
        public static string MSG_BLANK_CAPS {
            get {
                return ResourceManager.GetString("MSG_BLANK_CAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [blank].
        /// </summary>
        public static string MSG_BLANK_STRING {
            get {
                return ResourceManager.GetString("MSG_BLANK_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dummy.
        /// </summary>
        public static string MSG_DUMMY {
            get {
                return ResourceManager.GetString("MSG_DUMMY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DummyValue.
        /// </summary>
        public static string MSG_DUMMY_VALUE {
            get {
                return ResourceManager.GetString("MSG_DUMMY_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is evenly divisible by.
        /// </summary>
        public static string MSG_INTEGER_EVENLY_DIVISIBLE_BY {
            get {
                return ResourceManager.GetString("MSG_INTEGER_EVENLY_DIVISIBLE_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is even.
        /// </summary>
        public static string MSG_INTEGER_IS_EVEN {
            get {
                return ResourceManager.GetString("MSG_INTEGER_IS_EVEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is odd.
        /// </summary>
        public static string MSG_INTEGER_IS_ODD {
            get {
                return ResourceManager.GetString("MSG_INTEGER_IS_ODD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is.
        /// </summary>
        public static string MSG_IS {
            get {
                return ResourceManager.GetString("MSG_IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not.
        /// </summary>
        public static string MSG_IS_NOT {
            get {
                return ResourceManager.GetString("MSG_IS_NOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not exist.
        /// </summary>
        public static string MSG_OBJECT_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("MSG_OBJECT_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exists.
        /// </summary>
        public static string MSG_OBJECT_EXISTS {
            get {
                return ResourceManager.GetString("MSG_OBJECT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is absent.
        /// </summary>
        public static string MSG_OBJECT_IS_ABSENT {
            get {
                return ResourceManager.GetString("MSG_OBJECT_IS_ABSENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is missing.
        /// </summary>
        public static string MSG_OBJECT_IS_MISSING {
            get {
                return ResourceManager.GetString("MSG_OBJECT_IS_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is present.
        /// </summary>
        public static string MSG_OBJECT_IS_PRESENT {
            get {
                return ResourceManager.GetString("MSG_OBJECT_IS_PRESENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [null].
        /// </summary>
        public static string MSG_OBJECT_REFERENCE_IS_NULL {
            get {
                return ResourceManager.GetString("MSG_OBJECT_REFERENCE_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MSG_OBJECT_REFERENCE_IS_NULL_CAPS {
            get {
                return ResourceManager.GetString("MSG_OBJECT_REFERENCE_IS_NULL_CAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1:D} decimal).
        /// </summary>
        public static string MSG_STATUS_CODE {
            get {
                return ResourceManager.GetString("MSG_STATUS_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [empty].
        /// </summary>
        public static string MSG_STRING_IS_EMPTY {
            get {
                return ResourceManager.GetString("MSG_STRING_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [null or empty string].
        /// </summary>
        public static string MSG_STRING_IS_NULL_OR_EMPTY {
            get {
                return ResourceManager.GetString("MSG_STRING_IS_NULL_OR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [empty string].
        /// </summary>
        public static string MSG_THE_EMPTY_STRING {
            get {
                return ResourceManager.GetString("MSG_THE_EMPTY_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        public static string MSG_VALUE_IS_FALSE {
            get {
                return ResourceManager.GetString("MSG_VALUE_IS_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid.
        /// </summary>
        public static string MSG_VALUE_IS_INVALID {
            get {
                return ResourceManager.GetString("MSG_VALUE_IS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string MSG_VALUE_IS_TRUE {
            get {
                return ResourceManager.GetString("MSG_VALUE_IS_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to valid.
        /// </summary>
        public static string MSG_VALUE_IS_VALID {
            get {
                return ResourceManager.GetString("MSG_VALUE_IS_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REG_BINARY.
        /// </summary>
        public static string REGISTRY_VALUE_TYPE_BINARY {
            get {
                return ResourceManager.GetString("REGISTRY_VALUE_TYPE_BINARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REG_DWORD.
        /// </summary>
        public static string REGISTRY_VALUE_TYPE_DWORD {
            get {
                return ResourceManager.GetString("REGISTRY_VALUE_TYPE_DWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REG_EXPAND_SZ.
        /// </summary>
        public static string REGISTRY_VALUE_TYPE_EXPAND {
            get {
                return ResourceManager.GetString("REGISTRY_VALUE_TYPE_EXPAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REG_MULTI_SZ.
        /// </summary>
        public static string REGISTRY_VALUE_TYPE_MULTI {
            get {
                return ResourceManager.GetString("REGISTRY_VALUE_TYPE_MULTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REG_QWORD.
        /// </summary>
        public static string REGISTRY_VALUE_TYPE_QWORD {
            get {
                return ResourceManager.GetString("REGISTRY_VALUE_TYPE_QWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    at .
        /// </summary>
        public static string STACK_TRACE_ENTRY_PREFIX {
            get {
                return ResourceManager.GetString("STACK_TRACE_ENTRY_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [null].
        /// </summary>
        public static string VALUE_IS_NULL {
            get {
                return ResourceManager.GetString("VALUE_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bld..
        /// </summary>
        public static string VERSION_STRING_PART_BUILD_ABBR {
            get {
                return ResourceManager.GetString("VERSION_STRING_PART_BUILD_ABBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Number.
        /// </summary>
        public static string VERSION_STRING_PART_BUILD_LONG {
            get {
                return ResourceManager.GetString("VERSION_STRING_PART_BUILD_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string VERSION_STRING_PART_BUILD_SHORT {
            get {
                return ResourceManager.GetString("VERSION_STRING_PART_BUILD_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maj..
        /// </summary>
        public static string VERSION_STRING_PART_MAJOR_ABBR {
            get {
                return ResourceManager.GetString("VERSION_STRING_PART_MAJOR_ABBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Version.
        /// </summary>
        public static string VERSION_STRING_PART_MAJOR_LONG {
            get {
                return ResourceManager.GetString("VERSION_STRING_PART_MAJOR_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major.
        /// </summary>
        public static string VERSION_STRING_PART_MAJOR_SHORT {
            get {
                return ResourceManager.GetString("VERSION_STRING_PART_MAJOR_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min..
        /// </summary>
        public static string VERSION_STRING_PART_MINOR_ABBR {
            get {
                return ResourceManager.GetString("VERSION_STRING_PART_MINOR_ABBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Version.
        /// </summary>
        public static string VERSION_STRING_PART_MINOR_LONG {
            get {
                return ResourceManager.GetString("VERSION_STRING_PART_MINOR_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor.
        /// </summary>
        public static string VERSION_STRING_PART_MINOR_SHORT {
            get {
                return ResourceManager.GetString("VERSION_STRING_PART_MINOR_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rev..
        /// </summary>
        public static string VERSION_STRING_PART_REVNO_ABBR {
            get {
                return ResourceManager.GetString("VERSION_STRING_PART_REVNO_ABBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision.
        /// </summary>
        public static string VERSION_STRING_PART_REVNO_LONG {
            get {
                return ResourceManager.GetString("VERSION_STRING_PART_REVNO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision.
        /// </summary>
        public static string VERSION_STRING_PART_REVNO_SHORT {
            get {
                return ResourceManager.GetString("VERSION_STRING_PART_REVNO_SHORT", resourceCulture);
            }
        }
    }
}
