//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WizardWrx.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WizardWrx.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WizardWrx.
        /// </summary>
        public static string DEFAULT_EVENT_SOURCE_ID_STRING {
            get {
                return ResourceManager.GetString("DEFAULT_EVENT_SOURCE_ID_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified argument is a null reference..
        /// </summary>
        public static string ERRMSG_ARG_IS_NULL {
            get {
                return ResourceManager.GetString("ERRMSG_ARG_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument is a null reference or the empty string..
        /// </summary>
        public static string ERRMSG_ARG_IS_NULL_OR_EMPTY {
            get {
                return ResourceManager.GetString("ERRMSG_ARG_IS_NULL_OR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of {0} is out of range; it must be between {1} and {2}..
        /// </summary>
        public static string ERRMSG_ARG_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("ERRMSG_ARG_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process string {0}.
        /// </summary>
        public static string ERRMSG_BADSTRING {
            get {
                return ResourceManager.GetString("ERRMSG_BADSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The empty string is never valid in this context..
        /// </summary>
        public static string ERRMSG_EMPTY_STRING_NEVER_VALID {
            get {
                return ResourceManager.GetString("ERRMSG_EMPTY_STRING_NEVER_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file {0} is empty..
        /// </summary>
        public static string ERRMSG_FILE_IS_EMPTY {
            get {
                return ResourceManager.GetString("ERRMSG_FILE_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file {0} cannot be found..
        /// </summary>
        public static string ERRMSG_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERRMSG_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the first argument, pintegralValue, is invalid.{2}Argument value = {0}{2}Argument type  = {1}{2}{2}Limitations of the underlying formatting engine{2}restrict this method to integral types.{2}.
        /// </summary>
        public static string ERRMSG_INTEGER2HEXSTR_INVALID_INPUT {
            get {
                return ResourceManager.GetString("ERRMSG_INTEGER2HEXSTR_INVALID_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one command line argument is invalid..
        /// </summary>
        public static string ERRMSG_INVALID_COMMAND_LINE {
            get {
                return ResourceManager.GetString("ERRMSG_INVALID_COMMAND_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file {0}, record {1} is invalid..
        /// </summary>
        public static string ERRMSG_INVALID_FIELD_IN_INPUT_RECORD {
            get {
                return ResourceManager.GetString("ERRMSG_INVALID_FIELD_IN_INPUT_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A null reference to a string is never valid in this context..
        /// </summary>
        public static string ERRMSG_NULLREF_NEVER_VALID {
            get {
                return ResourceManager.GetString("ERRMSG_NULLREF_NEVER_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A run-time exception has occurred..
        /// </summary>
        public static string ERRMSG_RUNTIME {
            get {
                return ResourceManager.GetString("ERRMSG_RUNTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task completed successfully..
        /// </summary>
        public static string ERRMSG_SUCCESS {
            get {
                return ResourceManager.GetString("ERRMSG_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [null].
        /// </summary>
        public static string MSG_OBJECT_REFERENCE_IS_NULL {
            get {
                return ResourceManager.GetString("MSG_OBJECT_REFERENCE_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1:D} decimal).
        /// </summary>
        public static string MSG_STATUS_CODE {
            get {
                return ResourceManager.GetString("MSG_STATUS_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [null or empty string].
        /// </summary>
        public static string MSG_STRING_IS_NULL_OR_EMPTY {
            get {
                return ResourceManager.GetString("MSG_STRING_IS_NULL_OR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [empty string].
        /// </summary>
        public static string MSG_THE_EMPTY_STRING {
            get {
                return ResourceManager.GetString("MSG_THE_EMPTY_STRING", resourceCulture);
            }
        }
    }
}
