//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WizardWrx.HTTP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WizardWrx.HTTP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Taken Refresh getter routine was provided. Request must be abandoned..
        /// </summary>
        internal static string ERRMSG_NO_TOKEN_REFRESH_GETTER {
            get {
                return ResourceManager.GetString("ERRMSG_NO_TOKEN_REFRESH_GETTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for a new OAuth token to replace an expired token failed..
        /// </summary>
        internal static string ERRMSG_TOKEN_REFRESH_FAIL {
            get {
                return ResourceManager.GetString("ERRMSG_TOKEN_REFRESH_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdType=&quot;ImmutableId&quot;.
        /// </summary>
        internal static string HTTP_HDR_IMMUTABLE_ID {
            get {
                return ResourceManager.GetString("HTTP_HDR_IMMUTABLE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer.
        /// </summary>
        internal static string HTTP_HDR_PREFER {
            get {
                return ResourceManager.GetString("HTTP_HDR_PREFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [.
        /// </summary>
        internal static string JSON_ARRAY_PREFIX {
            get {
                return ResourceManager.GetString("JSON_ARRAY_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ].
        /// </summary>
        internal static string JSON_ARRAY_SUFFIX {
            get {
                return ResourceManager.GetString("JSON_ARRAY_SUFFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [].
        /// </summary>
        internal static string JSON_EMPTY_ARRAY {
            get {
                return ResourceManager.GetString("JSON_EMPTY_ARRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {}.
        /// </summary>
        internal static string JSON_EMPTY_OBJECT {
            get {
                return ResourceManager.GetString("JSON_EMPTY_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;.
        /// </summary>
        internal static string JSON_OBJECT_PREFIX {
            get {
                return ResourceManager.GetString("JSON_OBJECT_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        internal static string JSON_OBJECT_SUFFIX {
            get {
                return ResourceManager.GetString("JSON_OBJECT_SUFFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /messages.
        /// </summary>
        internal static string MESSAGES_ENDPOINT {
            get {
                return ResourceManager.GetString("MESSAGES_ENDPOINT", resourceCulture);
            }
        }
    }
}
