using System;
using System.Reflection;
using System.Runtime.CompilerServices;

using WizardWrx.DLLConfigurationManager;


namespace WizardWrx.HTTP
{
	/// <summary>
	/// Instances of this object represent options for configuring request
	/// behavior, including provision of exception logging tooling and OAuth
	/// token retrieval methods.
	/// </summary>
	public sealed class RequestOptions
	{
		/// <summary>
		/// This property represents the delegate signature for the
		/// <C>optional</C> callback method that receives log messages from the
		/// HTTP Request engine to which this instance is attached. The callback
		/// method is expected to handle the log message appropriately, such as
		/// by writing it to a log file, displaying it in a console, or sending
		/// it to a logging service. The additional parameters provide context
		/// about the source of the log message, including the member name,
		/// source file path, and line number where the log message was
		/// generated. This information can be useful for debugging and tracing
		/// the flow of execution in the HTTP engine, allowing developers to
		/// identify the specific location in the code where the log message
		/// originated. The use of CallerMemberName, CallerFilePath, and
		/// CallerLineNumber attributes allows the HTTP engine to automatically
		/// capture this contextual information without requiring the caller to
		/// explicitly provide it, making it easier to implement logging
		/// throughout the codebase. Overall, this delegate provides a flexible
		/// and powerful mechanism for logging messages from the HTTP engine
		/// while also capturing important contextual information for debugging
		/// purposes.
		/// </summary>
		/// <include file="../InternalDocumentationXmlCopyBooks/CallerInfo.xml"
		///          path="doc/members/member[@name='CallerInfoSummary']/*" />
		/// <param name="pstrLogMessage">
		/// <para>
		/// This string represents the log message generated by the HTTP engine.
		/// The content of the message can vary widely depending on the specific
		/// events and actions taking place within the engine, such as the
		/// initiation of a request, the receipt of a response, the occurrence
		/// of an error, or any other significant event that the engine deems
		/// worthy of logging. The message can include details about the request
		/// being processed, the response received, any exceptions encountered,
		/// or any other relevant information that can help developers under-
		/// stand the behavior of the HTTP engine and diagnose issues that may
		/// arise during its operation. 
		/// </para>
		/// <para>
		/// The log message can be formatted in a way that is consistent with
		/// the logging conventions used throughout the codebase, and may
		/// include timestamps, log levels, or other metadata to provide
		/// additional context for the message. Overall, the log message
		/// parameter serves as a crucial means of communication between the
		/// HTTP engine and the logging system, allowing developers to gain
		/// insights into the inner workings of the engine and troubleshoot any
		/// issues that may arise during its execution.
		/// </para>
		/// <para>
		/// All messages begin with a prefix that identifies the call site of
		/// the constructor or other method that reported it, so that log 
		/// entries can be easily traced back to their origin.
		/// </para>
		/// <para>
		/// The additional parameters, including memberName 
		/// (<paramref name="pstrMemberName"/>), sourceFilePath
		/// (<paramref name="pstrSourceFilePath"/>), and sourceLineNumber 
		/// (<paramref name="pintSourceLineNumber"/>), provide valuable context
		/// about the source of the log message. The memberName parameter
		/// indicates the name of the method or property where the log message
		/// was generated within the HTTP engine, allowing developers to
		/// pinpoint the specific location in the code that is responsible for
		/// the log message. The sourceFilePath parameter provides the file path
		/// of the source code file where the log message originated, which can
		/// be helpful for navigating to the relevant code when investigating
		/// issues. The sourceLineNumber parameter indicates the line number
		/// within the source code file where the log message was generated,
		/// providing precise information about the location where the message
		/// originated. Together, these parameters enable developers to quickly
		/// and efficiently trace the flow of execution within the HTTP engine
		/// and identify any potential issues or areas for improvement based on
		/// the logged messages.
		/// </para>
		/// </param>
		/// <include file="../InternalDocumentationXmlCopyBooks/CallerInfo.XML"
		///          path="doc/members/member[@name='CallerInfoParameters']/*" />
		public delegate void HttpEngineLogCallback (
			string pstrLogMessage ,
			[CallerMemberName] string memberName = SpecialStrings.EMPTY_STRING ,
			[CallerFilePath] string sourceFilePath = SpecialStrings.EMPTY_STRING ,
			[CallerLineNumber] int sourceLineNumber	 = MagicNumbers.ZERO );


		/// <summary>
		/// Let's be really clear about the shape of the default Accept HTTP header.
		/// </summary>
		public const string HTTP_ACCEPT_WILDCARD = @"*/*";


		/// <summary>
		/// Let's also document for posterity the Cache-Control directive that
		/// says "don't."
		/// </summary>
		public const string HTTP_NEVER_CACHE = @"no-cache";


		/// <summary>
		/// The Microsoft .NET Framework supports only two of the common compression
		/// formats, gzip and deflate.
		/// </summary>
		public const string HTTP_COMPRESSION_ALGS = @"gzip, deflate";


		/// <summary>
		/// This delegate signature represents a method that attempts to obtain an
		/// OAuth token and return it through an output parameter, along with the
		/// existing true/false outcome.
		/// </summary>
		/// <param name="token">
		/// When this method returns, contains the retrieved OAuth token if
		/// successful; otherwise, null.
		/// </param>
		/// <param name="logger">
		/// This represents the optional logger object for recording exceptions
		/// that arise during token retrieval.
		/// </param>
		/// <returns>
		/// The delegated function returns true if the token was successfully
		/// obtained; otherwise, it returns false and the <paramref name="token"/>
		/// value is undefined. The supplied copy of the access token is for use
		/// by the HTTP access method; the object that exposes the OAuth Access
		/// Token Getter is responsible for stashing a copy in protectd storage.
		/// </returns>
		public delegate bool OAuthTokenGetter (
			out string token ,
			ExceptionLogger logger = null
		);


		/// <summary>
		/// This read-only property returns an instance of ExceptionLogger for
		/// logging exceptions encountered during the processing of HTTP
		/// requests.
		/// </summary>
		public ExceptionLogger Logger { get; }


		/// <summary>
		///	This read-only property returns a delegate that processes log
		///	messages generated by the HTTP engine. The delegate is expected to
		///	handle the log messages appropriately, such as by writing them to a
		///	log file, displaying them in a console, or sending them to a logging
		///	service. The additional parameters provide context about the source
		///	of the log message, including the member name, source file path, and
		///	line number where the log message was generated. This information can
		///	be useful for debugging and tracing the flow of execution in the HTTP
		///	engine, allowing developers to identify the specific location in the
		///	code where the log message originated. The use of CallerMemberName,
		///	CallerFilePath, and CallerLineNumber attributes allows the HTTP
		///	engine to automatically capture this contextual information without
		///	requiring the caller to explicitly provide it, making it easier to
		///	implement logging throughout the codebase. Overall, this delegate
		///	provides a flexible and powerful mechanism for logging messages from
		///	the HTTP engine while also capturing important contextual
		///	information for debugging purposes.
		/// </summary>
		public HttpEngineLogCallback LogCallback { get; }


		/// <summary>
		/// This read-only property returns a delegate that retrieves OAuth Bearer
		/// tokens for inclusion in the Authorization header of HTTP requests.
		/// </summary>
		public OAuthTokenGetter TokenGetter { get; }


		/// <summary>
		/// When specified (not null), this string represents the value to 
		/// specify as the Accept HTTP header value.
		/// </summary>
		public string AcceptHeaderValue { get; }


		/// <summary>
		/// When specified (not null), this string represents the value to 
		/// specify as the Accept-Encoding HTTP header value.
		/// </summary>
		public string AcceptEncodingValue { get; }


		/// <summary>
		/// When specified (not null), this string represents the value to 
		/// specify as the Cache-Control HTTP header value.
		/// </summary>
		public string CacheControlValue { get; }


		/// <summary>
		/// This read-only string property gets the current OAuth token,
		/// retrieving and caching it if necessary.
		/// </summary>
		public string CurrentOAuthToken
		{
			get
			{
				// Only try to acquire a token when:
				//   1. A getter exists, and
				//   2. We haven't cached one yet
				if ( TokenGetter != null && _currentOAuthToken == null )
				{
					string strNewToken;

					if ( TokenGetter ( out strNewToken , Logger ) )
					{
						_currentOAuthToken = strNewToken;
					}   // if ( TokenGetter ( out strNewToken , Logger ) )
				}   // if ( TokenGetter != null && _currentOAuthToken == null )

				return _currentOAuthToken;
			}   // public string CurrentOAuthToken property get

			set
			{
				_currentOAuthToken = ( !string.IsNullOrEmpty ( value ) && value.Length > ListInfo.EMPTY_STRING_LENGTH
					? value
					: _currentOAuthToken );
			}   // public string CurrentOAuthToken property set
		}   // public string CurrentOAuthToken property


		/// <summary>
		/// <para>
		/// This read-only property returns a delegate that receives log
		/// messages from the HTTP engine to which this instance is attached.
		/// </para>
		/// <para>
		/// The callback method is expected to handle the log messages
		/// appropriately, such as by writing them to a log file, displaying
		/// them in a console, or sending them to a logging service. The
		/// additional parameters provide context about the source of the
		/// log message, including the member name, source file path, and
		/// line number where the log message was generated. This information
		/// can be useful for debugging and tracing the flow of execution in the
		/// HTTP engine, allowing developers to identify the specific location
		/// in the code where the log message originated. The use of
		/// CallerMemberName, CallerFilePath, and CallerLineNumber attributes
		/// allows the HTTP engine to automatically capture this contextual
		/// information without requiring the caller to explicitly provide it,
		/// making it easier to implement logging throughout the codebase.
		/// </para>
		/// <para>
		/// This delegate provides a flexible and powerful mechanism for
		/// logging messages from the HTTP engine while also capturing
		/// important contextual information for debugging purposes.
		/// </para>
		/// </summary>
		public HttpEngineLogCallback LoggerCallback { get; }


		/// <summary>
		/// This read-only integer property specifies the delay, <c>in
		/// seconds</c>, between retry attempts for a request that fails due to
		/// a transient error. The default value is <c>10</c>, which means that
		/// the HTTP engine will wait for 10 seconds before attempting to retry
		/// a failed request. This parameter allows developers to control the
		/// timing of retry attempts, providing a mechanism for introducing a
		/// delay between retries to avoid overwhelming the server or network
		/// with rapid-fire requests. By adjusting the retry delay, developers
		/// can optimize the balance between retrying failed requests and
		/// avoiding excessive delays in the overall request processing.
		/// </summary>
		public int RetryDelay { get; }


		/// <summary>
		/// This read-only integer property specifies the maximum number of times
		/// to retry a request that fails due to a transient error, such as a
		/// network issue or a server error. The default value is 10, which
		/// means that the HTTP engine will attempt to retry a failed request up
		/// to 10 times before giving up and returning an error to the caller.
		/// This parameter allows developers to control the behavior of the HTTP
		/// engine in the face of transient errors, providing a mechanism for
		/// automatically retrying requests that may succeed on subsequent
		/// attempts.
		/// </summary>
		public int RetryLimit { get; }


		/// <summary>
		/// The default constructor is hidden to enforce instatiation of only
		/// explicitly initialized instances.
		/// </summary>
		private RequestOptions ( ) { }


		/// <summary>
		/// The public constructor initializes both read-only properties of this
		/// class, so that consumers of this class must make their choices about
		/// these properties explicit.
		/// </summary>
		/// <param name="plogger">
		/// The ExceptionLogger instance to be used for logging Exceptions is
		/// optional; if no object is supplied, no Exception logging happens
		/// inside the other methods exposed by this library.
		/// </param>
		/// <param name="ptokenGetter">
		/// The delegate that retrieves OAuth Bearer tokens for inclusion in the
		/// Authorization header of HTTP requests is optional; if no delegate is
		/// provided, requests proceed without Authorization headers.
		/// </param>
		/// <param name="pstrInitialOAuthToken">
		/// This optional parameter allows the caller to supply an initial OAuth
		/// token that the class caches for future use. If this parameter is 
		/// null and <paramref name="ptokenGetter"/> is not null, the class 
		/// attempts to obtain a token the first time the property value is
		/// queried.
		/// </param>
		/// <param name="pstrAcceptHeaderValue">
		/// When specified, thiis string represents the value to include as the
		/// Accept HTTP header value. By default, the null value, "/", is added.
		/// </param>
		/// <param name="pstrAcceptEncodingValue">
		/// When specified, this string represents the value to include as the
		/// Accept-Encoding HTTP header value. By default, this value is null,
		/// and is, therefore, omitted.
		/// </param>
		/// <param name="pstrCacheControlValue">
		/// When specified, this string represents the value to include as the
		/// Cache-Control HTTP header value. The default  value is "no-cache".
		/// </param>
		/// <param name="pintRetryLimit">
		/// This integer specifies the maximum number of times to retry a
		/// request that fails due to a transient error, such as a network issue
		/// or a server error. The default value is 10, which means that the HTTP
		/// engine will attempt to retry a failed request up to 10 times before
		/// giving up and returning an error to the caller. This parameter allows
		/// developers to control the behavior of the HTTP engine in the face of
		/// transient errors, providing a mechanism for automatically retrying
		/// requests that may succeed on subsequent attempts.
		/// </param>
		/// <param name="pintRetryDelay">
		/// This integer specifies the delay, <c>in seconds</c>, between retry
		/// attempts for a request that fails due to a transient error. The
		/// default value is <c>10</c>, which means that the HTTP engine will wait for
		/// 10 seconds before attempting to retry a failed request. This
		/// parameter allows developers to control the timing of retry attempts,
		/// providing a mechanism for introducing a delay between retries to
		/// avoid overwhelming the server or network with rapid-fire requests.
		/// By adjusting the retry delay, developers can optimize the balance
		/// between retrying failed requests and avoiding excessive delays in
		/// the overall request processing.
		/// </param>
		/// <param name="pdiLogCallback">
		/// <para>
		/// This delegate is called to log messages from the HTTP engine. It is
		/// optional; if no delegate is provided, no logging occurs. 
		/// </para>
		/// <para>
		/// If logging is enabled, the delegate is expected to handle the log
		/// messages appropriately, such as by writing them to a log file,
		/// displaying them in a console, or sending them to a logging service.
		/// The additional parameters provide context about the source of the
		/// log message, including the member name, source file path, and line
		/// number where the log message was generated. This information can be
		/// useful for debugging and tracing the flow of execution in the HTTP
		/// engine, allowing developers to identify the specific location in the
		/// code where the log message originated. The use of CallerMemberName,
		/// Caller FilePath, and CallerLineNumber attributes allows the HTTP
		/// engine to automatically capture this contextual information without
		/// requiring the caller to explicitly provide it, making it easier to
		/// implement logging throughout the codebase. Overall, this delegate
		/// provides a flexible and powerful mechanism for logging messages from
		/// the HTTP engine while also capturing important contextual
		/// information for debugging purposes.
		/// </para>
		/// </param>
		public RequestOptions ( ExceptionLogger plogger = null , OAuthTokenGetter ptokenGetter = null , string pstrInitialOAuthToken = null , string pstrAcceptHeaderValue = HTTP_ACCEPT_WILDCARD , string pstrAcceptEncodingValue = null , string pstrCacheControlValue = HTTP_NEVER_CACHE , int pintRetryLimit = 10 , int pintRetryDelay = 10 , HttpEngineLogCallback pdiLogCallback = null )
		{
			Logger = plogger;
			TokenGetter = ptokenGetter;
			_currentOAuthToken = pstrInitialOAuthToken;
			AcceptHeaderValue = pstrAcceptHeaderValue;
			AcceptEncodingValue = pstrAcceptEncodingValue;
			CacheControlValue = pstrCacheControlValue;
			RetryLimit = pintRetryLimit;
			RetryDelay = pintRetryDelay;
			LoggerCallback = pdiLogCallback;
		}   // public RequestOptions



		/// <summary>
		/// This override of the ToString method provides a string
		/// representation of the RequestOptions instance, including the values
		/// of its properties. The string is formatted in a way that allows
		/// developers to easily understand the configuration of the
		/// RequestOptions instance, making it easier to debug and troubleshoot
		/// issues related to HTTP requests. The method uses helper functions to
		/// format the injected object reference and delegate information,
		/// ensuring that the output is clear and informative. Overall, this
		/// ToString override provides a valuable tool for developers to gain
		/// insights into the state of the RequestOptions instance and
		/// understand how it is configured for use with the HTTP engine.
		/// </summary>
		/// <returns>
		/// See the summary for details on the content and format of the
		/// returned string.
		/// </returns>
		public override string ToString ( )
		{
			return string.Concat (
				this.GetType ( ).Name , ": " ,
				"Logger=" , FormatInjectedObjectReference ( this.Logger ) , "; " ,
				"LogCallback=" , FormatDelegate ( this.LogCallback ) , "; " ,
				"TokenGetter=" , FormatDelegate ( this.TokenGetter ) , "; " ,
				"AcceptHeaderValue=" , ( this.AcceptHeaderValue ?? "null" ) , "; " ,
				"AcceptEncodingValue=" , ( this.AcceptEncodingValue ?? "null" ) , "; " ,
				"CacheControlValue=" , ( this.CacheControlValue ?? "null" ) , "; " ,
				"CurrentOAuthToken=" , ( this.CurrentOAuthToken != null ? "<redacted>" : "null" ) , "; " ,
				"LoggerCallback=" , FormatDelegate ( this.LoggerCallback ) , "; " ,
				"RetryDelay=" , this.RetryDelay.ToString ( ) , "; " ,
				"RetryLimit=" , this.RetryLimit.ToString ( )
			);
		}   // public override string ToString


		/// <summary>
		/// Create a string reprsentation of the supplied delegate, including
		/// the declaring type and method name, as well as the type of the
		/// target object (or "static" if the delegate represents a static
		/// method). This method is used to provide informative output in the
		/// ToString override, allowing developers to understand the
		/// configuration of the RequestOptions instance and the delegates it
		/// contains. If the supplied delegate is null, the method returns the
		/// string "null" to indicate that no delegate is assigned. Otherwise,
		/// the method constructs a string that includes the full name of the
		/// declaring type, the method name, and the type of the target object,
		/// providing a clear and concise representation of the delegate's
		/// configuration. Overall, this method serves as a valuable tool for
		/// developers to gain insights into the delegates used within the
		/// RequestOptions instance and understand how they are configured for
		/// use with the HTTP engine.
		/// </summary>
		/// <param name="delSig">
		/// This parameter represents the delegate for which to create a string
		/// representation. If the delegate is null, the method returns the
		/// string "[null]" to indicate that no delegate is assigned. Otherwise,
		/// the method constructs a string that includes the full name of the
		/// declaring type, the method name, and the type of the target object.
		/// </param>
		/// <returns>
		/// A string representation of the delegate, including the full name of the
		/// declaring type, the method name, and the type of the target object.
		/// If the delegate is null, the method returns the string "null".
		/// </returns>
		internal static string FormatDelegate ( Delegate delSig )
		{
			if ( delSig == null )
				return Common.Properties.Resources.VALUE_IS_NULL;

			MethodInfo method = delSig.Method;
			string declaring = method.DeclaringType != null
				? method.DeclaringType.FullName
				: "<unknown>";

			string target = delSig.Target != null
				? delSig.Target.GetType ( ).FullName
				: "static";

			return string.Concat (
				declaring , "." , method.Name ,
				" (target=" , target , ")"
			);
		}   // internal static string FormatDelegate


		/// <summary>
		/// Return a string representation of the supplied ExceptionLogger
		/// instance's BCL Type.
		/// </summary>
		/// <param name="el">
		/// The ExceptionLogger instance to format.
		/// </param>
		/// <returns>
		/// A string representation of the ExceptionLogger instance's BCL Type.
		/// </returns>
		internal static string FormatInjectedObjectReference ( ExceptionLogger el ) => ( el != null ? el.GetType ( ).FullName : Common.Properties.Resources.VALUE_IS_NULL );


		/// <summary>
		/// This private field caches the current OAuth token. Provision of this
		/// private property supports lazy loading of the token.
		/// </summary>
		private string _currentOAuthToken = null;
	}   // public sealed class RequestOptions
}   // partial namespace WizardWrx.HTT