//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WizardWrx.FormatStringEngine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WizardWrx.FormatStringEngine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Format compoent of the FormatItem is empty. The colon that signals its presence is immediately followed by a closing brace..
        /// </summary>
        internal static string ERRMSG_FORMAT_COMPONENT_IS_EMPTY {
            get {
                return ResourceManager.GetString("ERRMSG_FORMAT_COMPONENT_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {3}    Format String        = {0}{3}    Format Item Number   = {1}{3}    Proposed Replacement = {2}.
        /// </summary>
        internal static string ERRMSG_FORMAT_ITEM_DETAILS {
            get {
                return ResourceManager.GetString("ERRMSG_FORMAT_ITEM_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format substring of a FormatStringItem cannot be the empty string..
        /// </summary>
        internal static string ERRMSG_FORMAT_ITEM_ITEMFORMAT_SUBSTRING {
            get {
                return ResourceManager.GetString("ERRMSG_FORMAT_ITEM_ITEMFORMAT_SUBSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset = {0}, Character = {1}, Parser State = {2}, Message = {3}.
        /// </summary>
        internal static string ERRMSG_FORMAT_STRING_ERROR_TPL {
            get {
                return ResourceManager.GetString("ERRMSG_FORMAT_STRING_ERROR_TPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ApperanceOrder property of a FormatItem object must be greater than zero..
        /// </summary>
        internal static string ERRMSG_INVALID_APPEARANCE_ORDER {
            get {
                return ResourceManager.GetString("ERRMSG_INVALID_APPEARANCE_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TThe specified format item upgrade string is invalid.{0}.
        /// </summary>
        internal static string ERRMSG_INVALID_FORMAT_ITEM {
            get {
                return ResourceManager.GetString("ERRMSG_INVALID_FORMAT_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a positive integer..
        /// </summary>
        internal static string ERRMSG_INVALID_INDEX_FOR_FORMAT_ITEM {
            get {
                return ResourceManager.GetString("ERRMSG_INVALID_INDEX_FOR_FORMAT_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified RawLength value is invalid..
        /// </summary>
        internal static string ERRMSG_INVALID_RAW_LENGTH {
            get {
                return ResourceManager.GetString("ERRMSG_INVALID_RAW_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than zero..
        /// </summary>
        internal static string ERRMSG_INVALID_WIDTH_FORMAT_ITEM {
            get {
                return ResourceManager.GetString("ERRMSG_INVALID_WIDTH_FORMAT_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last format item in the string is incomplete..
        /// </summary>
        internal static string ERRMSG_LAST_ITEM_INCOMPLETE {
            get {
                return ResourceManager.GetString("ERRMSG_LAST_ITEM_INCOMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MinimumWidth property is already initialized. Call the UpdateMinimumWidth method to add digits..
        /// </summary>
        internal static string ERRMSG_MINIMUM_WIDTH_ALREADY_INITIALIZED {
            get {
                return ResourceManager.GetString("ERRMSG_MINIMUM_WIDTH_ALREADY_INITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified format string is missing the specified format item.{0}.
        /// </summary>
        internal static string ERRMSG_MISSING_FORMAT_ITEM {
            get {
                return ResourceManager.GetString("ERRMSG_MISSING_FORMAT_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nondigit immediately following left brace..
        /// </summary>
        internal static string ERRMSG_NONDIGIT_AFTER_LEFTBRACE {
            get {
                return ResourceManager.GetString("ERRMSG_NONDIGIT_AFTER_LEFTBRACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RawLength property is immutable, and has already been set..
        /// </summary>
        internal static string ERRMSG_RAW_LENGTH_ALREADY_SET {
            get {
                return ResourceManager.GetString("ERRMSG_RAW_LENGTH_ALREADY_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApperanceOrder property of FormatItem object.
        /// </summary>
        internal static string FORMAT_ITEM_APPEARANCE_ORDER {
            get {
                return ResourceManager.GetString("FORMAT_ITEM_APPEARANCE_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index property of FormatStringItem object.
        /// </summary>
        internal static string FORMAT_ITEM_INDEX_PROPERTY {
            get {
                return ResourceManager.GetString("FORMAT_ITEM_INDEX_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index property of FormatStringItem object.
        /// </summary>
        internal static string FORMAT_ITEM_ITEMFORMAT_SUBSTRING {
            get {
                return ResourceManager.GetString("FORMAT_ITEM_ITEMFORMAT_SUBSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinimumWidth property of FormatStringItem object.
        /// </summary>
        internal static string FORMAT_ITEM_MINIMUM_WIDTH_PROPERTY {
            get {
                return ResourceManager.GetString("FORMAT_ITEM_MINIMUM_WIDTH_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FormatString property.
        /// </summary>
        internal static string PARSER_INPUT_STRING {
            get {
                return ResourceManager.GetString("PARSER_INPUT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RawLength Property Value of FormatItem Object.
        /// </summary>
        internal static string RAW_LENGTH_PROPERTY_LABEL {
            get {
                return ResourceManager.GetString("RAW_LENGTH_PROPERTY_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}.
        /// </summary>
        internal static string X_OF_Y_FIXED_TEXT {
            get {
                return ResourceManager.GetString("X_OF_Y_FIXED_TEXT", resourceCulture);
            }
        }
    }
}
