//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WizardWrx.AssemblyUtils.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WizardWrx.AssemblyUtils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssemblyGUID.
        /// </summary>
        internal static string ATTRIBUTE_SHORT_NAME_ASSEMBLY_GUID {
            get {
                return ResourceManager.GetString("ATTRIBUTE_SHORT_NAME_ASSEMBLY_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string ATTRIBUTE_SHORT_NAME_COMPANY {
            get {
                return ResourceManager.GetString("ATTRIBUTE_SHORT_NAME_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string ATTRIBUTE_SHORT_NAME_COPYRIGHT {
            get {
                return ResourceManager.GetString("ATTRIBUTE_SHORT_NAME_COPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        internal static string ATTRIBUTE_SHORT_NAME_CULTURE {
            get {
                return ResourceManager.GetString("ATTRIBUTE_SHORT_NAME_CULTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ATTRIBUTE_SHORT_NAME_DESCRIPTION {
            get {
                return ResourceManager.GetString("ATTRIBUTE_SHORT_NAME_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileVersion.
        /// </summary>
        internal static string ATTRIBUTE_SHORT_NAME_FILEVERSION {
            get {
                return ResourceManager.GetString("ATTRIBUTE_SHORT_NAME_FILEVERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string ATTRIBUTE_SHORT_NAME_PRODUCT {
            get {
                return ResourceManager.GetString("ATTRIBUTE_SHORT_NAME_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string ATTRIBUTE_SHORT_NAME_TITLE {
            get {
                return ResourceManager.GetString("ATTRIBUTE_SHORT_NAME_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trademark.
        /// </summary>
        internal static string ATTRIBUTE_SHORT_NAME_TRADEMARK {
            get {
                return ResourceManager.GetString("ATTRIBUTE_SHORT_NAME_TRADEMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string ATTRIBUTE_SHORT_NAME_VERSION {
            get {
                return ResourceManager.GetString("ATTRIBUTE_SHORT_NAME_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{{0} (FullName = {1}, IsLoaded = {2})}}.
        /// </summary>
        internal static string DEPENDENT_ASSEMBLYINFO_TOSTRING_TEMPLATE {
            get {
                return ResourceManager.GetString("DEPENDENT_ASSEMBLYINFO_TOSTRING_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library method {0} was unable to create directory {1}..
        /// </summary>
        internal static string ERRMSG_CREATE_DIRECTORY_FAILED {
            get {
                return ResourceManager.GetString("ERRMSG_CREATE_DIRECTORY_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties of direct dependent assemblies follow.{0}.
        /// </summary>
        internal static string MSG_ASM_DEPENDENTS_DETAILS_HEAD {
            get {
                return ResourceManager.GetString("MSG_ASM_DEPENDENTS_DETAILS_HEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}End of list for Assembly {0}:{1}.
        /// </summary>
        internal static string MSG_ASM_DEPENDENTS_DETAILS_TAIL {
            get {
                return ResourceManager.GetString("MSG_ASM_DEPENDENTS_DETAILS_TAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2}Assembly {0} depends upon the following {1} assemblies:{2}.
        /// </summary>
        internal static string MSG_ASM_DEPENDENTS_LIST_HEADER {
            get {
                return ResourceManager.GetString("MSG_ASM_DEPENDENTS_LIST_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}End of list for Assembly {0}:{1}.
        /// </summary>
        internal static string MSG_ASM_DEPENDENTS_LIST_TAIL {
            get {
                return ResourceManager.GetString("MSG_ASM_DEPENDENTS_LIST_TAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         AssemblyFileBaseName = {0}.
        /// </summary>
        internal static string MSG_ASM_PROPS_ASSEMBLYFILEBASENAME {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_ASSEMBLYFILEBASENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         AssemblyFileName     = {0}{1}.
        /// </summary>
        internal static string MSG_ASM_PROPS_ASSEMBLYFILENAME {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_ASSEMBLYFILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         AssemblyGuidString   = {0}.
        /// </summary>
        internal static string MSG_ASM_PROPS_ASSEMBLYGUIDSTRING {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_ASSEMBLYGUIDSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         AssemblyVersion      = {0} (per AssemblyName.GetAssemblyName).
        /// </summary>
        internal static string MSG_ASM_PROPS_ASSEMBLYVERSION {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_ASSEMBLYVERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         AssembyDirName       = {0}.
        /// </summary>
        internal static string MSG_ASM_PROPS_ASSEMBYDIRNAME {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_ASSEMBYDIRNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         Comments             = {0}{1}.
        /// </summary>
        internal static string MSG_ASM_PROPS_COMMENTS {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         CompanyName          = {0}.
        /// </summary>
        internal static string MSG_ASM_PROPS_COMPANYNAME {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_COMPANYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         Culture              = {0}.
        /// </summary>
        internal static string MSG_ASM_PROPS_CULTURE {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_CULTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         Description          = {0}.
        /// </summary>
        internal static string MSG_ASM_PROPS_DESCRIPTION {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         File Creation Date   = {0} ({1} UTC).
        /// </summary>
        internal static string MSG_ASM_PROPS_FILE_CREATION_DATE {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_FILE_CREATION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         File Modified Date   = {0} ({1} UTC).
        /// </summary>
        internal static string MSG_ASM_PROPS_FILE_MODIFIED_DATE {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_FILE_MODIFIED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         LegalCopyright       = {0}.
        /// </summary>
        internal static string MSG_ASM_PROPS_LEGALCOPYRIGHT {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_LEGALCOPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         LegalTrademarks      = {0}.
        /// </summary>
        internal static string MSG_ASM_PROPS_LEGALTRADEMARKS {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_LEGALTRADEMARKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         ProductName          = {0}.
        /// </summary>
        internal static string MSG_ASM_PROPS_PRODUCTNAME {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_PRODUCTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         PublicKeyToken       = {0}.
        /// </summary>
        internal static string MSG_ASM_PROPS_PUBLICKEYTOKEN {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_PUBLICKEYTOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         Runtime Version      = {0}.
        /// </summary>
        internal static string MSG_ASM_PROPS_RUNTIME_VERSION {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_RUNTIME_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Selected properties of assembly {0} of {1}, {2}:{3}.
        /// </summary>
        internal static string MSG_ASM_PROPS_SELECTED_DLL_PROPS_BEGIN {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_SELECTED_DLL_PROPS_BEGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2}    End of selected properties of assembly {0} of {1}{2}.
        /// </summary>
        internal static string MSG_ASM_PROPS_SELECTED_DLL_PROPS_END {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_SELECTED_DLL_PROPS_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         VersionString        = {0} (per System.Diagnostics.FileVersionInfo.GetVersionInfo).
        /// </summary>
        internal static string MSG_ASM_PROPS_VERSIONSTRING {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_VERSIONSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file, {1}{0}{1}, cannot be found..
        /// </summary>
        internal static string MSG_GETSUBSYST_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("MSG_GETSUBSYST_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An I/O error occurred while reading input file {1}{2}Exception type: {0}{2}Additional details are in the inner exception..
        /// </summary>
        internal static string MSG_GETSUBSYST_FILE_READ_ERROR {
            get {
                return ResourceManager.GetString("MSG_GETSUBSYST_FILE_READ_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An I/O error occurred while reading input file {0}{3}Only {1} of the expected {2} bytes were read..
        /// </summary>
        internal static string MSG_GETSUBSYST_FILE_READ_SHORT {
            get {
                return ResourceManager.GetString("MSG_GETSUBSYST_FILE_READ_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file, {1}{0}{1}, is too short to be a valid Portable Executable.{4}Actual File Size (bytes) = {2:N0}{4}Minimum Size of PE File  = {3:N0}{4}.
        /// </summary>
        internal static string MSG_GETSUBSYST_FILE_TOO_SMALL {
            get {
                return ResourceManager.GetString("MSG_GETSUBSYST_FILE_TOO_SMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file name pointer is the empty string..
        /// </summary>
        internal static string MSG_GETSUBSYST_FILENAME_POINTER_EMPTY_STRING {
            get {
                return ResourceManager.GetString("MSG_GETSUBSYST_FILENAME_POINTER_EMPTY_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An {0} exception was raised by the Microsoft .NET runtime engine while processing input file {1}.{2}Additional details are in the inner exception..
        /// </summary>
        internal static string MSG_GETSUBSYST_GENERAL_EXCEPTION {
            get {
                return ResourceManager.GetString("MSG_GETSUBSYST_GENERAL_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system cannot find the magic WORD in file {0}..
        /// </summary>
        internal static string MSG_GETSUBSYST_NO_MAGIC {
            get {
                return ResourceManager.GetString("MSG_GETSUBSYST_NO_MAGIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system cannot find the NT header magic DWORD in file {0}..
        /// </summary>
        internal static string MSG_GETSUBSYST_NO_NT_MAGIC {
            get {
                return ResourceManager.GetString("MSG_GETSUBSYST_NO_NT_MAGIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NT header block pointer is invalid in file {0}{2}Pointer value = 0x{1:x8} ({1:N0} decimal.).
        /// </summary>
        internal static string MSG_GETSUBSYST_NO_NT_SIGNATURE {
            get {
                return ResourceManager.GetString("MSG_GETSUBSYST_NO_NT_SIGNATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file name pointer is invalid (NULL)..
        /// </summary>
        internal static string MSG_GETSUBSYST_NULL_FILENAME_POINTER {
            get {
                return ResourceManager.GetString("MSG_GETSUBSYST_NULL_FILENAME_POINTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native.
        /// </summary>
        internal static string MSG_IMAGE_SUBSYSTEM_NATIVE {
            get {
                return ResourceManager.GetString("MSG_IMAGE_SUBSYSTEM_NATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image doesn&apos;t require a subsystem..
        /// </summary>
        internal static string MSG_IMAGE_SUBSYSTEM_NATIVE_LONG {
            get {
                return ResourceManager.GetString("MSG_IMAGE_SUBSYSTEM_NATIVE_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native Win9x driver.
        /// </summary>
        internal static string MSG_IMAGE_SUBSYSTEM_NATIVE_WINDOWS {
            get {
                return ResourceManager.GetString("MSG_IMAGE_SUBSYSTEM_NATIVE_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is a native Win9x driver..
        /// </summary>
        internal static string MSG_IMAGE_SUBSYSTEM_NATIVE_WINDOWS_LONG {
            get {
                return ResourceManager.GetString("MSG_IMAGE_SUBSYSTEM_NATIVE_WINDOWS_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS/2 character.
        /// </summary>
        internal static string MSG_IMAGE_SUBSYSTEM_OS2_CUI {
            get {
                return ResourceManager.GetString("MSG_IMAGE_SUBSYSTEM_OS2_CUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image runs in the OS/2 character subsystem..
        /// </summary>
        internal static string MSG_IMAGE_SUBSYSTEM_OS2_CUI_LONG {
            get {
                return ResourceManager.GetString("MSG_IMAGE_SUBSYSTEM_OS2_CUI_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posix character.
        /// </summary>
        internal static string MSG_IMAGE_SUBSYSTEM_POSIX_CUI {
            get {
                return ResourceManager.GetString("MSG_IMAGE_SUBSYSTEM_POSIX_CUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image runs in the Posix character subsystem..
        /// </summary>
        internal static string MSG_IMAGE_SUBSYSTEM_POSIX_CUI_LONG {
            get {
                return ResourceManager.GetString("MSG_IMAGE_SUBSYSTEM_POSIX_CUI_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string MSG_IMAGE_SUBSYSTEM_UNKNOWN {
            get {
                return ResourceManager.GetString("MSG_IMAGE_SUBSYSTEM_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown subsystem..
        /// </summary>
        internal static string MSG_IMAGE_SUBSYSTEM_UNKNOWN_LONG {
            get {
                return ResourceManager.GetString("MSG_IMAGE_SUBSYSTEM_UNKNOWN_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows CE.
        /// </summary>
        internal static string MSG_IMAGE_SUBSYSTEM_WINDOWS_CE_GUI {
            get {
                return ResourceManager.GetString("MSG_IMAGE_SUBSYSTEM_WINDOWS_CE_GUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image runs in the Windows CE subsystem..
        /// </summary>
        internal static string MSG_IMAGE_SUBSYSTEM_WINDOWS_CE_GUI_LONG {
            get {
                return ResourceManager.GetString("MSG_IMAGE_SUBSYSTEM_WINDOWS_CE_GUI_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows character.
        /// </summary>
        internal static string MSG_IMAGE_SUBSYSTEM_WINDOWS_CUI {
            get {
                return ResourceManager.GetString("MSG_IMAGE_SUBSYSTEM_WINDOWS_CUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image runs in the Windows character subsystem..
        /// </summary>
        internal static string MSG_IMAGE_SUBSYSTEM_WINDOWS_CUI_LONG {
            get {
                return ResourceManager.GetString("MSG_IMAGE_SUBSYSTEM_WINDOWS_CUI_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows GUI.
        /// </summary>
        internal static string MSG_IMAGE_SUBSYSTEM_WINDOWS_GUI {
            get {
                return ResourceManager.GetString("MSG_IMAGE_SUBSYSTEM_WINDOWS_GUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image runs in the Windows GUI subsystem..
        /// </summary>
        internal static string MSG_IMAGE_SUBSYSTEM_WINDOWS_GUI_LONG {
            get {
                return ResourceManager.GetString("MSG_IMAGE_SUBSYSTEM_WINDOWS_GUI_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReflectedAssemblyContainer for Assembly {0}&quot;.
        /// </summary>
        internal static string MSG_PRIVATE_DOMAIN_NAME_TEMPLATE {
            get {
                return ResourceManager.GetString("MSG_PRIVATE_DOMAIN_NAME_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only assemblies that run in the character mode subsystem are supported.{2}The subsytem ID of the entry assembly is {0} ({1})..
        /// </summary>
        internal static string MSG_UNSUPPORTED_PE_SUBSYSTEM {
            get {
                return ResourceManager.GetString("MSG_UNSUPPORTED_PE_SUBSYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subsystem ID must be greater than zero and less than ten..
        /// </summary>
        internal static string MSG_XLATE_SUBSYST_INVALID_ID {
            get {
                return ResourceManager.GetString("MSG_XLATE_SUBSYST_INVALID_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{{0} (Subsystem ID = {1} ({2})}}.
        /// </summary>
        internal static string PESUBSYSTEMINFO_TOSTRING_TEMPLATE {
            get {
                return ResourceManager.GetString("PESUBSYSTEMINFO_TOSTRING_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName,AssemblyFileBaseName,AssemblyFileName,AssemblyGuidString,AssembyDirName,Comments,CompanyName,Culture,Description,FileCreationDate,FileModifiedDate,LegalCopyright,LegalTrademarks,ProductName,PublicKeyToken,RuntimeVersion,VersionString.
        /// </summary>
        internal static string REPORT_FIELD_NAMES {
            get {
                return ResourceManager.GetString("REPORT_FIELD_NAMES", resourceCulture);
            }
        }
    }
}
