//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLLServices2TestStand.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DLLServices2TestStand.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, version {1} BOJ{4}{2} ({3} UTC){4}.
        /// </summary>
        public static string BOJ_MSG_TPL {
            get {
                return ResourceManager.GetString("BOJ_MSG_TPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chop Test {0}: Input String Length  = {1}, Value = {2}{5}             Output String Length = {3}, Value = {4}{5}.
        /// </summary>
        public static string CHOP_TEST_REPORT {
            get {
                return ResourceManager.GetString("CHOP_TEST_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectDependentAssemblyEnumerator.
        /// </summary>
        public static string CMDARG_DIRECT_DEPENDENT_ASSEMBLY_ENUMERATION {
            get {
                return ResourceManager.GetString("CMDARG_DIRECT_DEPENDENT_ASSEMBLY_ENUMERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NameValueCollectionFromEmbbededList.
        /// </summary>
        public static string CMDARG_EMBEDDED_NVC_TEST {
            get {
                return ResourceManager.GetString("CMDARG_EMBEDDED_NVC_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnumExcpetionGUIDs.
        /// </summary>
        public static string CMDARG_ENUMERATE_EXCEPTION_GUIDS {
            get {
                return ResourceManager.GetString("CMDARG_ENUMERATE_EXCEPTION_GUIDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventMessageCleanupTests.
        /// </summary>
        public static string CMDARG_EVENT_MSG_CLEANUP_TESTS {
            get {
                return ResourceManager.GetString("CMDARG_EVENT_MSG_CLEANUP_TESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TruncateValueToOneLine.
        /// </summary>
        public static string CMDARG_EXERCISE_TRUNCATEVALUETOONELINE {
            get {
                return ResourceManager.GetString("CMDARG_EXERCISE_TRUNCATEVALUETOONELINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenerateExceptionMessageFormatTable.
        /// </summary>
        public static string CMDARG_GENERATE_EXCEPTION_MESSAGE_FORMAT_TABLE {
            get {
                return ResourceManager.GetString("CMDARG_GENERATE_EXCEPTION_MESSAGE_FORMAT_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnumerateStringResourcesInAssembly.
        /// </summary>
        public static string CMDARG_LIST_COMMON_STRINGS {
            get {
                return ResourceManager.GetString("CMDARG_LIST_COMMON_STRINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListObjectProperties.
        /// </summary>
        public static string CMDARG_LIST_OBJECT_PROPERTIES {
            get {
                return ResourceManager.GetString("CMDARG_LIST_OBJECT_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RedirectionDetection.
        /// </summary>
        public static string CMDARG_REDIRECTION_DETECTION {
            get {
                return ResourceManager.GetString("CMDARG_REDIRECTION_DETECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RedirectionStateTests.
        /// </summary>
        public static string CMDARG_REDIRECTION_STATE_TESTS {
            get {
                return ResourceManager.GetString("CMDARG_REDIRECTION_STATE_TESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StringFixups.
        /// </summary>
        public static string CMDARG_STRING_FIXUPS {
            get {
                return ResourceManager.GetString("CMDARG_STRING_FIXUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2}This text should appear as {0} letters on a {1} background.{2}.
        /// </summary>
        public static string COLOR_MESSAGE_TEXT {
            get {
                return ResourceManager.GetString("COLOR_MESSAGE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default colors of a {0} exception, as seen through{4}{1}, are {2} text on a {3} background.{4}.
        /// </summary>
        public static string DEFAULT_EXCEPTION_COLORS_MESSAGE {
            get {
                return ResourceManager.GetString("DEFAULT_EXCEPTION_COLORS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the GetDefaultErrorMessageColors method.
        /// </summary>
        public static string DEFAULT_EXCEPTION_COLORS_METHOD_1 {
            get {
                return ResourceManager.GetString("DEFAULT_EXCEPTION_COLORS_METHOD_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the GetDefaultMessageColors method.
        /// </summary>
        public static string DEFAULT_EXCEPTION_COLORS_METHOD_2 {
            get {
                return ResourceManager.GetString("DEFAULT_EXCEPTION_COLORS_METHOD_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to individdual properties.
        /// </summary>
        public static string DEFAULT_EXCEPTION_COLORS_PROPERTIES {
            get {
                return ResourceManager.GetString("DEFAULT_EXCEPTION_COLORS_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} EOJ{2}Running time = {1}{2}Press ENTER to exit the program..
        /// </summary>
        public static string EOJ_MSG_TPL {
            get {
                return ResourceManager.GetString("EOJ_MSG_TPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified test index, {0}, is too high.{2}Valid values are positive integers less than {1}..
        /// </summary>
        public static string ERRMSG_INVALID_TEST_INDEX {
            get {
                return ResourceManager.GetString("ERRMSG_INVALID_TEST_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must belong to the LimitConditon enumeration..
        /// </summary>
        public static string ERRMSG_LIMIT_CONDITON {
            get {
                return ResourceManager.GetString("ERRMSG_LIMIT_CONDITON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must belong to the LimitValue enumeration..
        /// </summary>
        public static string ERRMSG_LIMIT_VALUE {
            get {
                return ResourceManager.GetString("ERRMSG_LIMIT_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This literal is made plural if the error count is greater than 1..
        /// </summary>
        public static string ERRMSG_LITERAL_ERROR {
            get {
                return ResourceManager.GetString("ERRMSG_LITERAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABORTING: Method NewClassTests_20140914.{0} failed, returning a status code of {1}.
        /// </summary>
        public static string ERRMSG_NEW_CLASS_TESTS_20140914 {
            get {
                return ResourceManager.GetString("ERRMSG_NEW_CLASS_TESTS_20140914", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A run-time exception was caught and reported..
        /// </summary>
        public static string ERRMSG_RUNTIME {
            get {
                return ResourceManager.GetString("ERRMSG_RUNTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing completed without errors..
        /// </summary>
        public static string ERRMSG_SUCCESS {
            get {
                return ResourceManager.GetString("ERRMSG_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fatal.
        /// </summary>
        public static string EXCEPTION_IS_FATAL {
            get {
                return ResourceManager.GetString("EXCEPTION_IS_FATAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recoverable.
        /// </summary>
        public static string EXCEPTION_IS_RECOVERABLE {
            get {
                return ResourceManager.GetString("EXCEPTION_IS_RECOVERABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         Character index {0}: {1}.
        /// </summary>
        public static string IDS_ASCII_CHARACTER_INFO {
            get {
                return ResourceManager.GetString("IDS_ASCII_CHARACTER_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     This first of two tables lists character codes, rendering the printable, hexadecimal, and decimal value of each.{0}.
        /// </summary>
        public static string IDS_ASCII_TABLE_CHARACTER_PROPERTIES {
            get {
                return ResourceManager.GetString("IDS_ASCII_TABLE_CHARACTER_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}    The ASCII_Table_Gen method will now enumerate the ASCII_Character_Display_Table{0}.
        /// </summary>
        public static string IDS_ASCII_TABLE_ENUMERATION {
            get {
                return ResourceManager.GetString("IDS_ASCII_TABLE_ENUMERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character {0} ({1}): URL Encoding = {2}, Display Value = {3}{4}.
        /// </summary>
        public static string IDS_ASCII_TABLE_ITEM {
            get {
                return ResourceManager.GetString("IDS_ASCII_TABLE_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}The following tables list key attributes of every ASCII character.{0}.
        /// </summary>
        public static string IDS_ASCII_TABLE_PREAMBLE {
            get {
                return ResourceManager.GetString("IDS_ASCII_TABLE_PREAMBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the label row in the master input file is invalid.{3}It should contain {0} TAB delimited fields.{3}The supplied label contains {1} fields.{3}The label row follows.{2}{3}.
        /// </summary>
        public static string IDS_BAD_MASTER_LABEL_ROW {
            get {
                return ResourceManager.GetString("IDS_BAD_MASTER_LABEL_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison must involve objects of the same type..
        /// </summary>
        public static string IDS_COMPARETO_MISMATCH {
            get {
                return ResourceManager.GetString("IDS_COMPARETO_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source of Test Data.
        /// </summary>
        public static string IDS_DATA_SOURCE {
            get {
                return ResourceManager.GetString("IDS_DATA_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully Qualified Name of Input File.
        /// </summary>
        public static string IDS_DATAFILE_FQFN {
            get {
                return ResourceManager.GetString("IDS_DATAFILE_FQFN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Lines in Input File.
        /// </summary>
        public static string IDS_DATAFILE_LINES {
            get {
                return ResourceManager.GetString("IDS_DATAFILE_LINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Input File Last Modified.
        /// </summary>
        public static string IDS_DATAFILE_MODDATE {
            get {
                return ResourceManager.GetString("IDS_DATAFILE_MODDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size, in Bytes, of Input File.
        /// </summary>
        public static string IDS_DATAFILE_SIZE {
            get {
                return ResourceManager.GetString("IDS_DATAFILE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master File.
        /// </summary>
        public static string IDS_DESCR_MASTER_FILE {
            get {
                return ResourceManager.GetString("IDS_DESCR_MASTER_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Items File.
        /// </summary>
        public static string IDS_DESCR_NEWITEMS_FILE {
            get {
                return ResourceManager.GetString("IDS_DESCR_NEWITEMS_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output File.
        /// </summary>
        public static string IDS_DESCR_OUTPUT_FILE {
            get {
                return ResourceManager.GetString("IDS_DESCR_OUTPUT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input files are inconsistent{2}Label row of master file = {0}{2}Label Row of current file = {1}.
        /// </summary>
        public static string IDS_INCONSISTENT_INPUTS {
            get {
                return ResourceManager.GetString("IDS_INCONSISTENT_INPUTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key field {0} in record {1} is invalid. All keys must be integers..
        /// </summary>
        public static string IDS_INVALID_KEY {
            get {
                return ResourceManager.GetString("IDS_INVALID_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of Longest Line.
        /// </summary>
        public static string IDS_LENGTH_OF_LONGEST {
            get {
                return ResourceManager.GetString("IDS_LENGTH_OF_LONGEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Begin Tests of MaxStringLength Method:{0}.
        /// </summary>
        public static string IDS_MAX_STRLEN_BEGIN {
            get {
                return ResourceManager.GetString("IDS_MAX_STRLEN_BEGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}MaxStringLength tests completed.{0}.
        /// </summary>
        public static string IDS_MAX_STRLEN_END {
            get {
                return ResourceManager.GetString("IDS_MAX_STRLEN_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Begin Tests of MergeNewItemsIntoArray Method:{0}.
        /// </summary>
        public static string IDS_MERGENEWITEMSINTOARRAY_BEGIN {
            get {
                return ResourceManager.GetString("IDS_MERGENEWITEMSINTOARRAY_BEGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}MergeNewItemsIntoArray tests completed.{0}.
        /// </summary>
        public static string IDS_MERGENEWITEMSINTOARRAY_END {
            get {
                return ResourceManager.GetString("IDS_MERGENEWITEMSINTOARRAY_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description\tFileName\tModDate\tSize\tLineCount.
        /// </summary>
        public static string IDS_MERGENEWITEMSINTOARRAY_LABELS {
            get {
                return ResourceManager.GetString("IDS_MERGENEWITEMSINTOARRAY_LABELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        public static string IDS_MSG_BEGIN {
            get {
                return ResourceManager.GetString("IDS_MSG_BEGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string IDS_MSG_DONE {
            get {
                return ResourceManager.GetString("IDS_MSG_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string IDS_MSG_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("IDS_MSG_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest Label = {0}.
        /// </summary>
        public static string IDS_MSG_LONGEST_LABEL {
            get {
                return ResourceManager.GetString("IDS_MSG_LONGEST_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest Value = {0}{1}.
        /// </summary>
        public static string IDS_MSG_LONGEST_VALUE {
            get {
                return ResourceManager.GetString("IDS_MSG_LONGEST_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Label 1.
        /// </summary>
        public static string IDS_MSG_REPORT_LABEL_1 {
            get {
                return ResourceManager.GetString("IDS_MSG_REPORT_LABEL_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Label 2.
        /// </summary>
        public static string IDS_MSG_REPORT_LABEL_2 {
            get {
                return ResourceManager.GetString("IDS_MSG_REPORT_LABEL_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Label 3.
        /// </summary>
        public static string IDS_MSG_REPORT_LABEL_3 {
            get {
                return ResourceManager.GetString("IDS_MSG_REPORT_LABEL_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Label 4.
        /// </summary>
        public static string IDS_MSG_REPORT_LABEL_4 {
            get {
                return ResourceManager.GetString("IDS_MSG_REPORT_LABEL_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Label 5.
        /// </summary>
        public static string IDS_MSG_REPORT_LABEL_5 {
            get {
                return ResourceManager.GetString("IDS_MSG_REPORT_LABEL_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This long string is for testing another routine, for use in right-alingining numeric values in a report..
        /// </summary>
        public static string IDS_REALLY_LONG_STRING {
            get {
                return ResourceManager.GetString("IDS_REALLY_LONG_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Test # {0}:{1}.
        /// </summary>
        public static string IDS_TEST_BEGIN {
            get {
                return ResourceManager.GetString("IDS_TEST_BEGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}    Test # {0} done{1}.
        /// </summary>
        public static string IDS_TEST_END {
            get {
                return ResourceManager.GetString("IDS_TEST_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAIL.
        /// </summary>
        public static string IDS_TEST_FAIL {
            get {
                return ResourceManager.GetString("IDS_TEST_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        public static string IDS_TEST_PASS {
            get {
                return ResourceManager.GetString("IDS_TEST_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal variable _enmDataSource has an unsupported value of {0}..
        /// </summary>
        public static string IDS_UNSUPPORTED_DATASOURCE {
            get {
                return ResourceManager.GetString("IDS_UNSUPPORTED_DATASOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppConfig_OutgoingMailServer_Mapping.TXT.
        /// </summary>
        public static string MAIL_SERVER_KEY_MAP_FILENAME {
            get {
                return ResourceManager.GetString("MAIL_SERVER_KEY_MAP_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutgoingMailServer_PropertyName	SettingsPropertyValueCollection_KeyName.
        /// </summary>
        public static string MAIL_SERVER_KEY_MAP_LABEL_ROW {
            get {
                return ResourceManager.GetString("MAIL_SERVER_KEY_MAP_LABEL_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item\tActivity_Date\tOpen\tHigh\tLow\tClose\tAdjustedClose\tVolume\tDividendAmount\tSplitCoefficient.
        /// </summary>
        public static string MESSAGE_CONTAINS_ESCAPED_TABS {
            get {
                return ResourceManager.GetString("MESSAGE_CONTAINS_ESCAPED_TABS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Empty String}.
        /// </summary>
        public static string MESSAGE_EMPTY_STRING {
            get {
                return ResourceManager.GetString("MESSAGE_EMPTY_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Null String}.
        /// </summary>
        public static string MESSAGE_NULL_STRING {
            get {
                return ResourceManager.GetString("MESSAGE_NULL_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Absolute Location of Entry Assembly                = {0}.
        /// </summary>
        public static string MSG_APP_DOMAIN_ENTRY_ASM_LOCATION {
            get {
                return ResourceManager.GetString("MSG_APP_DOMAIN_ENTRY_ASM_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}    Name of Entry Assembly                             = {0}.
        /// </summary>
        public static string MSG_APP_DOMAIN_ENTRY_ASM_NAME {
            get {
                return ResourceManager.GetString("MSG_APP_DOMAIN_ENTRY_ASM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {3}    Entry Assembly Subsystem                           = {0} ({1}): {2}{3}.
        /// </summary>
        public static string MSG_APP_DOMAIN_SUBSYSTEM {
            get {
                return ResourceManager.GetString("MSG_APP_DOMAIN_SUBSYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}Fully qualified program name, per StateManager GetAssemblyFQFN method = {0}.
        /// </summary>
        public static string MSG_ASBSOLUTE_ASSEMBLYNAME {
            get {
                return ResourceManager.GetString("MSG_ASBSOLUTE_ASSEMBLYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character {0,3}: Numerical Value = {1,3} ({2} hex), Display Value = {3}, HTML Entity = {4}.
        /// </summary>
        public static string MSG_ASCII_TABLE_DETAIL {
            get {
                return ResourceManager.GetString("MSG_ASCII_TABLE_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}The ASCII Table details are reproduced as a separate text file, {0}.{1}.
        /// </summary>
        public static string MSG_ASCII_TABLES_REPORT {
            get {
                return ResourceManager.GetString("MSG_ASCII_TABLES_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2}Executable Subsystem = {0}: {1}{2}.
        /// </summary>
        public static string MSG_ASSEMBLY_SUBSYSTEM {
            get {
                return ResourceManager.GetString("MSG_ASSEMBLY_SUBSYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     BaseDirectory                                      = {0}.
        /// </summary>
        public static string MSG_BASE_DIRECTORY_NAME {
            get {
                return ResourceManager.GetString("MSG_BASE_DIRECTORY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Current Machine Time     = {0} ({1} UTC).
        /// </summary>
        public static string MSG_CURRENT_MACHINE_TIME {
            get {
                return ResourceManager.GetString("MSG_CURRENT_MACHINE_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     ApplicationIdentity                                = NULL.
        /// </summary>
        public static string MSG_DFLT_APP_IDENTITY_NULL {
            get {
                return ResourceManager.GetString("MSG_DFLT_APP_IDENTITY_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     ActivationContext.Identity.CodeBase                = {0}.
        /// </summary>
        public static string MSG_DFLT_DOMAIN_IDENTITY_CODEBASE {
            get {
                return ResourceManager.GetString("MSG_DFLT_DOMAIN_IDENTITY_CODEBASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     ActivationContext.Identity.FullName                = {0}.
        /// </summary>
        public static string MSG_DFLT_DOMAIN_IDENTITY_FULLNAME {
            get {
                return ResourceManager.GetString("MSG_DFLT_DOMAIN_IDENTITY_FULLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}End of property listing for default application domain{0}.
        /// </summary>
        public static string MSG_DFLT_DOMAIN_PROPS_FOOTER {
            get {
                return ResourceManager.GetString("MSG_DFLT_DOMAIN_PROPS_FOOTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}The default application domain exhibits the following properties.{0}.
        /// </summary>
        public static string MSG_DFLT_DOMAIN_PROPS_HEADER {
            get {
                return ResourceManager.GetString("MSG_DFLT_DOMAIN_PROPS_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     SetupInformation                                   = NULL.
        /// </summary>
        public static string MSG_DFLT_SETUP_INFO_NULL {
            get {
                return ResourceManager.GetString("MSG_DFLT_SETUP_INFO_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     DomainManager.SetupInformation.ApplicationBase     = {0}.
        /// </summary>
        public static string MSG_DOMAIN_MGR_APP_BASE {
            get {
                return ResourceManager.GetString("MSG_DOMAIN_MGR_APP_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     DomainManager.SetupInformation.ApplicationName     = {0}.
        /// </summary>
        public static string MSG_DOMAIN_MGR_APP_NAME {
            get {
                return ResourceManager.GetString("MSG_DOMAIN_MGR_APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     DomainManager.FriendlyName                         = {0}.
        /// </summary>
        public static string MSG_DOMAIN_MGR_FRIENDLY_NAME {
            get {
                return ResourceManager.GetString("MSG_DOMAIN_MGR_FRIENDLY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     DomainManager.Id                                   = {0}.
        /// </summary>
        public static string MSG_DOMAIN_MGR_ID {
            get {
                return ResourceManager.GetString("MSG_DOMAIN_MGR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     DomainManager.EntryAssembly.FullName               = {0}.
        /// </summary>
        public static string MSG_ENTRY_ASM_FULLNAME {
            get {
                return ResourceManager.GetString("MSG_ENTRY_ASM_FULLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     DomainManager.EntryAssembly.Location               = {0}.
        /// </summary>
        public static string MSG_ENTRY_ASM_LOCATION {
            get {
                return ResourceManager.GetString("MSG_ENTRY_ASM_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}Total exceptions logged = {0}.
        /// </summary>
        public static string MSG_EXCETIONS_COUNTED {
            get {
                return ResourceManager.GetString("MSG_EXCETIONS_COUNTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details for error {0}:.
        /// </summary>
        public static string MSG_FORMAT_ERROR_DETAILS {
            get {
                return ResourceManager.GetString("MSG_FORMAT_ERROR_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attached to a console.
        /// </summary>
        public static string MSG_HANDLE_IS_ATTACHED {
            get {
                return ResourceManager.GetString("MSG_HANDLE_IS_ATTACHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redirected to a file or pipe.
        /// </summary>
        public static string MSG_HANDLE_IS_REDIRECTED {
            get {
                return ResourceManager.GetString("MSG_HANDLE_IS_REDIRECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        public static string MSG_HANDLE_IS_UNDEFINED {
            get {
                return ResourceManager.GetString("MSG_HANDLE_IS_UNDEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HandleBase.
        /// </summary>
        public static string MSG_HANDLEBASE_NULL {
            get {
                return ResourceManager.GetString("MSG_HANDLEBASE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2}Total keys in embedded resource file {0} = {1}{2}.
        /// </summary>
        public static string MSG_KEY_MAP_COUNT {
            get {
                return ResourceManager.GetString("MSG_KEY_MAP_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop Limit Values: Start = {0}{2}                   Stop  = {1}{2}.
        /// </summary>
        public static string MSG_LOOP_LIMIT_VALUES {
            get {
                return ResourceManager.GetString("MSG_LOOP_LIMIT_VALUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Evaluate loop state with a Equal To Limit:{0}.
        /// </summary>
        public static string MSG_LOOP_STATE_EQ {
            get {
                return ResourceManager.GetString("MSG_LOOP_STATE_EQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Evaluate loop state with a Greater Than or Equal To Limit:{0}.
        /// </summary>
        public static string MSG_LOOP_STATE_GE {
            get {
                return ResourceManager.GetString("MSG_LOOP_STATE_GE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Evaluate loop state with a Greater Than Limit:{0}.
        /// </summary>
        public static string MSG_LOOP_STATE_GT {
            get {
                return ResourceManager.GetString("MSG_LOOP_STATE_GT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Evaluate loop state with a Less Than or Equal To Limit:{0}.
        /// </summary>
        public static string MSG_LOOP_STATE_LE {
            get {
                return ResourceManager.GetString("MSG_LOOP_STATE_LE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Evaluate loop state with a Less Than Limit:{0}.
        /// </summary>
        public static string MSG_LOOP_STATE_LT {
            get {
                return ResourceManager.GetString("MSG_LOOP_STATE_LT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{5}{1}{5}{2}{5}{3}{5}{4}{5}.
        /// </summary>
        public static string MSG_LOOP_STATE_TABLE_DATA {
            get {
                return ResourceManager.GetString("MSG_LOOP_STATE_TABLE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index{0}First{0}Next{0}More{0}Last.
        /// </summary>
        public static string MSG_LOOP_STATE_TABLE_LABELS {
            get {
                return ResourceManager.GetString("MSG_LOOP_STATE_TABLE_LABELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case {0} of {1}:{2}.
        /// </summary>
        public static string MSG_NEW_TEST {
            get {
                return ResourceManager.GetString("MSG_NEW_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     DomainManager                                      = NULL.
        /// </summary>
        public static string MSG_NO_DOMAIN_MANAGER {
            get {
                return ResourceManager.GetString("MSG_NO_DOMAIN_MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     ActivationContext                                  = NULL.
        /// </summary>
        public static string MSG_NULL_ACTIVATION_CONTEXT {
            get {
                return ResourceManager.GetString("MSG_NULL_ACTIVATION_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Argument penmAlignment, an Alignment.
        /// </summary>
        public static string MSG_PENMALIGNMENT {
            get {
                return ResourceManager.GetString("MSG_PENMALIGNMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press ENTER to resume the program..
        /// </summary>
        public static string MSG_PHOTO_OP {
            get {
                return ResourceManager.GetString("MSG_PHOTO_OP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PInvokeW32.
        /// </summary>
        public static string MSG_PINVOKE_WIN32 {
            get {
                return ResourceManager.GetString("MSG_PINVOKE_WIN32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Name of Entry Assembly   = {0}.
        /// </summary>
        public static string MSG_PROCESS_ENTRY_ASM_NAME {
            get {
                return ResourceManager.GetString("MSG_PROCESS_ENTRY_ASM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Entry Assembly Subsystem = {0} ({1}): {2}{3}.
        /// </summary>
        public static string MSG_PROCESS_ENTRY_ASM_SUBSYSTEM {
            get {
                return ResourceManager.GetString("MSG_PROCESS_ENTRY_ASM_SUBSYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Process ID               = 0x{0:X8} ({1} decimal){2}.
        /// </summary>
        public static string MSG_PROCESS_ID {
            get {
                return ResourceManager.GetString("MSG_PROCESS_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}End of property listing for current process{0}.
        /// </summary>
        public static string MSG_PROCESS_PROPERTIES_FOOTER {
            get {
                return ResourceManager.GetString("MSG_PROCESS_PROPERTIES_FOOTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}The current process has the following properties.{0}.
        /// </summary>
        public static string MSG_PROCESS_PROPERTIES_HEADER {
            get {
                return ResourceManager.GetString("MSG_PROCESS_PROPERTIES_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Process Startup Time     = {0} ({1} UTC).
        /// </summary>
        public static string MSG_PROCESS_STARTUP_TIME {
            get {
                return ResourceManager.GetString("MSG_PROCESS_STARTUP_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Argument pstrFormatString, a string&lt;.
        /// </summary>
        public static string MSG_PSTRFORMATSTRING {
            get {
                return ResourceManager.GetString("MSG_PSTRFORMATSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Argument puintItemIndex, an uint.
        /// </summary>
        public static string MSG_PUINTITEMINDEX {
            get {
                return ResourceManager.GetString("MSG_PUINTITEMINDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Argument puintMaximumWidth, an uint&lt;.
        /// </summary>
        public static string MSG_PUINTMAXIMUMWIDTH {
            get {
                return ResourceManager.GetString("MSG_PUINTMAXIMUMWIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirection State Test Method = {0}: Iterations   = {1}{5}                                            Start Time   = {2}{5}                                            Finish Time  = {3}{5}                                            Elapsed Time = {4}{5}{5}.
        /// </summary>
        public static string MSG_REDIRECTION_STATE_TEST_TIMING {
            get {
                return ResourceManager.GetString("MSG_REDIRECTION_STATE_TEST_TIMING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Public method RegistryValues.RegQueryValue: Key Name   = {0}{4}                                                Value Name = {1}{4}                                                Value Type = {2}{4}                                                Value Data = {3}{4}.
        /// </summary>
        public static string MSG_REG_KEY_VALUE {
            get {
                return ResourceManager.GetString("MSG_REG_KEY_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}The DisplayOrder properties are auto-generated.{0}.
        /// </summary>
        public static string MSG_REPORT_DETAILS_AUTO_ORDERED {
            get {
                return ResourceManager.GetString("MSG_REPORT_DETAILS_AUTO_ORDERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}The DisplayOrder properties of selected items were explicitly set.{0}.
        /// </summary>
        public static string MSG_REPORT_DETAILS_SELECTIVELY_OVERRIDDEN {
            get {
                return ResourceManager.GetString("MSG_REPORT_DETAILS_SELECTIVELY_OVERRIDDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}The test collection is UNsorted.{0}.
        /// </summary>
        public static string MSG_REPORT_DETAILS_UNSORTED {
            get {
                return ResourceManager.GetString("MSG_REPORT_DETAILS_UNSORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token 0 = {0}, Token 1 ={1}, Token 2 - {2}, Token 3 = {3}.
        /// </summary>
        public static string MSG_SAMPLE_FORMAT_STRING {
            get {
                return ResourceManager.GetString("MSG_SAMPLE_FORMAT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2}    Sample Format: Before Transformation = {0}{2}                   After Transformation  = {1}{2}.
        /// </summary>
        public static string MSG_SHOW_SAMPLE_BEFORE_AND_AFTER {
            get {
                return ResourceManager.GetString("MSG_SHOW_SAMPLE_BEFORE_AND_AFTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The colors shown below were read from WizardWrx.DllServices2.dll.config.{0}.
        /// </summary>
        public static string MSG_SHOWING_CONFIGURED_COLORS {
            get {
                return ResourceManager.GetString("MSG_SHOWING_CONFIGURED_COLORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}The next screen displays selected properties of the library that is about to be exercised.{0}.
        /// </summary>
        public static string MSG_SHOWING_LIBRARY_INFO {
            get {
                return ResourceManager.GetString("MSG_SHOWING_LIBRARY_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The colors shown below were supplied by the test stand program.{0}.
        /// </summary>
        public static string MSG_SHOWING_PROGRAMMATIC_COLORS {
            get {
                return ResourceManager.GetString("MSG_SHOWING_PROGRAMMATIC_COLORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console handle {0} is {1}{2}.
        /// </summary>
        public static string MSG_STANDARD_HANDLE_STATE {
            get {
                return ResourceManager.GetString("MSG_STANDARD_HANDLE_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Error (STDERR, a. k. a., Console.Error).
        /// </summary>
        public static string MSG_STDERR {
            get {
                return ResourceManager.GetString("MSG_STDERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Input (STDIN, a. k. a., Console.In).
        /// </summary>
        public static string MSG_STDIN {
            get {
                return ResourceManager.GetString("MSG_STDIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Output (STDOUT, a. k. a., Console.Out).
        /// </summary>
        public static string MSG_STDOUT {
            get {
                return ResourceManager.GetString("MSG_STDOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  substrings.
        /// </summary>
        public static string MSG_SUBSTRING_SUMMARY_1 {
            get {
                return ResourceManager.GetString("MSG_SUBSTRING_SUMMARY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , as follows:.
        /// </summary>
        public static string MSG_SUBSTRING_SUMMARY_2 {
            get {
                return ResourceManager.GetString("MSG_SUBSTRING_SUMMARY_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         Value # {0} = {1}{2}.
        /// </summary>
        public static string MSG_SUBSTRING_VALUE {
            get {
                return ResourceManager.GetString("MSG_SUBSTRING_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unless Idiom Tests Begin:{0}.
        /// </summary>
        public static string MSG_UNLESS_BEGIN {
            get {
                return ResourceManager.GetString("MSG_UNLESS_BEGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Unless Idiom Tests Done!{0}.
        /// </summary>
        public static string MSG_UNLESS_END {
            get {
                return ResourceManager.GetString("MSG_UNLESS_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Boolean Expression = {0}, Unless = {1}.
        /// </summary>
        public static string MSG_UNLESS_WHAT {
            get {
                return ResourceManager.GetString("MSG_UNLESS_WHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         Upgraded Format String.
        /// </summary>
        public static string MSG_UPGRADED_FORMAT {
            get {
                return ResourceManager.GetString("MSG_UPGRADED_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Testing StateManager.GetAssemblyProductAndVersion:{0}.
        /// </summary>
        public static string MSG_VERSIONIFNO_TESTS_BEGIN {
            get {
                return ResourceManager.GetString("MSG_VERSIONIFNO_TESTS_BEGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Entry Assembly product version ({0}, {1} parts) = {2}.
        /// </summary>
        public static string MSG_VERSIONINFO {
            get {
                return ResourceManager.GetString("MSG_VERSIONINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}    Entry Assembly default product version = {0}{1}{1}StateManager.GetAssemblyProductAndVersion Tests Completed{1}.
        /// </summary>
        public static string MSG_VERSIONINFO_TESTS_DONE {
            get {
                return ResourceManager.GetString("MSG_VERSIONINFO_TESTS_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}CAUTION: Command line argument {0} trumps all others.{1}         Remaining arguments will be ignored.{1}.
        /// </summary>
        public static string MSG_WARNING_SUPERFLUOUS_ARGS_DISCARDED {
            get {
                return ResourceManager.GetString("MSG_WARNING_SUPERFLUOUS_ARGS_DISCARDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Public method RegExpSupport.FileMatchesRegExpMask = {0,-5}, for filename = {1} and mask = {2}.
        /// </summary>
        public static string REGEXP_TEST_ALL_BUT_LAST {
            get {
                return ResourceManager.GetString("REGEXP_TEST_ALL_BUT_LAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Public method RegExpSupport.FileMatchesRegExpMask = {0,-5}, for filename = {1} and mask = {2}{3}.
        /// </summary>
        public static string REGEXP_TEST_LAST {
            get {
                return ResourceManager.GetString("REGEXP_TEST_LAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Test Case {0}{1}.
        /// </summary>
        public static string TEST_EXCEPTION_LABEL {
            get {
                return ResourceManager.GetString("TEST_EXCEPTION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Exception Message Number {0} .
        /// </summary>
        public static string TEST_EXCEPTION_MESSAGE {
            get {
                return ResourceManager.GetString("TEST_EXCEPTION_MESSAGE", resourceCulture);
            }
        }
    }
}
