//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLLServices2TestStand.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$$DATADIRNAME$$\\ExceptionGUIDsListingFile.TXT")]
        public string ExceptionGUIDsListingFile {
            get {
                return ((string)(this["ExceptionGUIDsListingFile"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$$DATADIRNAME$$\\ExcceptionMessageTable.TXT")]
        public string ExcceptionMessageTable {
            get {
                return ((string)(this["ExcceptionMessageTable"]));
            }
            set {
                this["ExcceptionMessageTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$$DATADIRNAME$$\\DependentAssemblyInfoReport.TXT")]
        public string DependentAssemblyInfoReport {
            get {
                return ((string)(this["DependentAssemblyInfoReport"]));
            }
            set {
                this["DependentAssemblyInfoReport"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Test_Data")]
        public string Data_Directory {
            get {
                return ((string)(this["Data_Directory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$$DATADIRNAME$$\\MergeNewItemsIntoArray_Master.TXT")]
        public string MergeNewItemsIntoArray_Master {
            get {
                return ((string)(this["MergeNewItemsIntoArray_Master"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$$DATADIRNAME$$\\MergeNewItemsIntoArray_Output_$$CASENBR$$.TXT")]
        public string MergeNewItemsIntoArray_Outputs {
            get {
                return ((string)(this["MergeNewItemsIntoArray_Outputs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$$DATADIRNAME$$\\MergeNewItemsIntoArray_Summary.TXT")]
        public string MergeNewItemsIntoArray_Summary {
            get {
                return ((string)(this["MergeNewItemsIntoArray_Summary"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$$DATADIRNAME$$\\MaxStringLength.TXT")]
        public string MaxStringLength_Input {
            get {
                return ((string)(this["MaxStringLength_Input"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MergeNewItemsIntoArray_Case_??.TXT")]
        public string MergeNewItemsIntoArray_Cases {
            get {
                return ((string)(this["MergeNewItemsIntoArray_Cases"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string SuccessfulOutcomeMessageColor {
            get {
                return ((string)(this["SuccessfulOutcomeMessageColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public string SuccessfulOutcomeMessageBackgroundColor {
            get {
                return ((string)(this["SuccessfulOutcomeMessageBackgroundColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$$DATADIRNAME$$\\Common_Strings.TSV")]
        public string Common_Strings_Report_FileName {
            get {
                return ((string)(this["Common_Strings_Report_FileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$$DATADIRNAME$$\\DllServicesTestStand_Strings.TSV")]
        public string Startup_Assembly_Strings_Report_FileName {
            get {
                return ((string)(this["Startup_Assembly_Strings_Report_FileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$$DATADIRNAME$$\\DependentAssemblies_Test_Case_Data.TSV")]
        public string DependentAssemblies_Test_Case_Data_FileName {
            get {
                return ((string)(this["DependentAssemblies_Test_Case_Data_FileName"]));
            }
        }
    }
}
