@echo off
echo BOJ %0
echo.

call XCopyD.CMD "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\DLLServices2\WizardWrx.DLLServices2.dll.config" C:\Users\DAVE\Documents\Programming\Visual_Studio_6\DLL\ProcessInfo\CDeclToStdCallMigrationTool\CDeclToStdCallMigrationTool\bin\Debug /f /v /r /y
call XCopyD.CMD "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\DLLServices2\WizardWrx.DLLServices2.dll.config" "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\Console_Apps\MassUpdateColorIndex\MassUpdateColorIndex\bin\Debug" /f /v /r /y
call XCopyD.CMD "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\DLLServices2\WizardWrx.DLLServices2.dll.config" "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\Console_Apps\MassUpdateColorIndex\MassUpdateColorIndex\bin\Release" /f /v /r /y
call XCopyD.CMD "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\DLLServices2\WizardWrx.DLLServices2.dll.config" "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\Console_Apps\MultiCat\MultiCat\bin\Debug" /f /v /r /y
call XCopyD.CMD "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\DLLServices2\WizardWrx.DLLServices2.dll.config" "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\Console_Apps\NFiles\NFiles\bin\Debug" /f /v /r /y
call XCopyD.CMD "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\DLLServices2\WizardWrx.DLLServices2.dll.config" "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\NOLANB\DataEaseDirectoryReader\DataEase\bin\Debug" /f /v /r /y
call XCopyD.CMD "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\DLLServices2\WizardWrx.DLLServices2.dll.config" "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\NOLANB\DataEaseDirectoryReader\DataEase\bin\Release" /f /v /r /y
call XCopyD.CMD "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\DLLServices2\WizardWrx.DLLServices2.dll.config" "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\NOLANB\EZPayWebPmtsNotifier\EZPayWebPmtsNotifier\bin\Debug" /f /v /r /y
call XCopyD.CMD "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\DLLServices2\WizardWrx.DLLServices2.dll.config" "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\NOLANB\EZPayWebPmtsNotifier\EZPayWebPmtsNotifier\bin\Release" /f /v /r /y
call XCopyD.CMD "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\DLLServices2\WizardWrx.DLLServices2.dll.config" "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\Tools_for_Programmers\BitView\BitView\bin\Debug" /f /v /r /y
call XCopyD.CMD "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\DLLServices2\WizardWrx.DLLServices2.dll.config" "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\Tools_for_Programmers\MemView\MemView\bin\Debug" /f /v /r /y
call XCopyD.CMD "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\DLLServices2\WizardWrx.DLLServices2.dll.config" "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\DLLServices2\obj\Debug" /f /v /r /y
call XCopyD.CMD "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\DLLServices2\WizardWrx.DLLServices2.dll.config" "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\DLLServices2\obj\Release" /f /v /r /y
call XCopyD.CMD "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\DLLServices2\WizardWrx.DLLServices2.dll.config" "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\MailForAllApps\MailForAllApps\bin\Debug" /f /v /r /y
call XCopyD.CMD "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\DLLServices2\WizardWrx.DLLServices2.dll.config" "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\MailForAllApps\MailForAllApps\bin\Release" /f /v /r /y
call XCopyD.CMD "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\DLLServices2\WizardWrx.DLLServices2.dll.config" "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\SharedUtl4\FormatStringEngine\bin\Debug" /f /v /r /y
call XCopyD.CMD "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\DLLServices2\WizardWrx.DLLServices2.dll.config" "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\SharedUtl4\SharedUtl4\bin\Debug" /f /v /r /y
call XCopyD.CMD "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\DLLServices2\WizardWrx.DLLServices2.dll.config" "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\SharedUtl4\SharedUtl4\bin\Release" /f /v /r /y
call XCopyD.CMD "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\DLLServices2\WizardWrx.DLLServices2.dll.config" "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\WinFormsHelpers\WinFormsHelpers\bin\Debug" /f /v /r /y
call XCopyD.CMD "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\DLLServices2\WizardWrx.DLLServices2.dll.config" "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\WinFormsHelpers\WinFormsHelpers\bin\Release" /f /v /r /y

call XCopyD.CMD "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\DLLServices2\WizardWrx.DLLServices2.dll.config" "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\_Laboratory\CSharp_Lab\bin\Debug" /f /v /r /y
call XCopyD.CMD "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\DLLServices2\WizardWrx.DLLServices2.dll.config" "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\_Laboratory\CSharp_Lab\bin\x86\Debug" /f /v /r /y
call XCopyD.CMD "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\DLLServices2\WizardWrx.DLLServices2.dll.config" "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\_Laboratory\CSharp_Lab\CSharp_Lab\bin\Debug" /f /v /r /y
call XCopyD.CMD "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\DLLServices2\WizardWrx.DLLServices2.dll.config" "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\_Laboratory\CSharp_Lab\CSharp_Lab\bin\x86\Debug" /f /v /r /y

echo.
echo EOJ %~nx0
