@echo off
echo BOJ %~0
echo.

call XCopyF.CMD C:\bin\CreateFileWithRetry.dll "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\tools\CreateFileWithRetry.dll" /f /v
call XCopyF.CMD C:\bin\FixedStringBuffers.dll "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\tools\FixedStringBuffers.dll" /f /v
call XCopyF.CMD C:\bin\P6CStringLib1.dll "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\tools\P6CStringLib1.dll" /f /v
call XCopyF.CMD C:\bin\P6VersionInfo.dll "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\tools\P6VersionInfo.dll" /f /v
call XCopyF.CMD C:\bin\ProcessInfo.dll "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\tools\ProcessInfo.dll" /f /v
call XCopyF.CMD C:\bin\SafeMemCpy.dll "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\tools\SafeMemCpy.dll" /f /v
call XCopyF.CMD C:\bin\WizardWrx.ApplicationHelpers.dll "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\tools\WizardWrx.ApplicationHelpers.dll" /f /v
call XCopyF.CMD C:\bin\WizardWrx.ApplicationHelpers.pdb "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\tools\WizardWrx.ApplicationHelpers.pdb" /f /v
call XCopyF.CMD C:\bin\WizardWrx.ApplicationHelpers.xml "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\tools\WizardWrx.ApplicationHelpers.xml" /f /v
call XCopyF.CMD C:\bin\WizardWrx.ConsoleAppAids.dll "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\tools\WizardWrx.ConsoleAppAids.dll" /f /v
call XCopyF.CMD C:\bin\WizardWrx.ConsoleAppAids.pdb "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\tools\WizardWrx.ConsoleAppAids.pdb" /f /v
call XCopyF.CMD C:\bin\WizardWrx.ConsoleAppAids.xml "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\tools\WizardWrx.ConsoleAppAids.xml" /f /v
call XCopyF.CMD C:\bin\WizardWrx.DateMath.dll "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\tools\WizardWrx.DateMath.dll" /f /v
call XCopyF.CMD C:\bin\WizardWrx.DateMath.pdb "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\tools\WizardWrx.DateMath.pdb" /f /v
call XCopyF.CMD C:\bin\WizardWrx.DateMath.xml "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\tools\WizardWrx.DateMath.xml" /f /v
call XCopyF.CMD C:\bin\WizardWrx.SharedUtl2.dll "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\tools\WizardWrx.SharedUtl2.dll" /f /v
call XCopyF.CMD C:\bin\WizardWrx.SharedUtl2.pdb "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\tools\WizardWrx.SharedUtl2.pdb" /f /v
call XCopyF.CMD C:\bin\WizardWrx.SharedUtl2.xml "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\tools\WizardWrx.SharedUtl2.xml" /f /v
call XCopyF.CMD C:\bin\wwBldNbrMgr.exe "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\tools\wwBldNbrMgr.exe" /f /v
call XCopyF.CMD C:\bin\wwBldNbrMgr.exe.config "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\tools\wwBldNbrMgr.exe.config" /f /v
call XCopyF.CMD C:\bin\wwBldNbrMgr.pdb "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\tools\wwBldNbrMgr.pdb" /f /v
call XCopyF.CMD C:\bin\WWConAid.dll "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\tools\WWConAid.dll" /f /v
call XCopyF.CMD C:\bin\WWDateLib.dll "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\tools\WWDateLib.dll" /f /v
call XCopyF.CMD C:\bin\WWKernelLibWrapper.dll "C:\Users\DAVE\Documents\Visual Studio 2013\Projects\WizardWrx_Libs\DLLServices2\tools\WWKernelLibWrapper.dll" /f /v

echo.
echo BOJ %~nx0
